### ISSUE TITLE
PM2 i 0 stopped working

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#101]
Hi,

I am using iframely source code for quite some time and it is very helpful. Last, I took the version 0.8.10 and after that I started getting issues with PM2 -i 0.

If I now run command as PM2 start server.js -i 0, it is getting stuck, anything changed.

Regards,
Manik Mittal

**Comment by nleush** [comment]
Hi.
I've tested locally this version - works ok.

Can you show log after server restart? Call:

    pm2 restart all
    pm2 logs

**Comment by manikmi** [comment]
Thanks Nazar,
I tried running pm2 kill and then tried again. It worked.

Thanks,
Manik Mittal
