### ISSUE TITLE
Issue with open source code

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#102]
Hi,

I am using the iframely open source code. The following url works fine on iframely site, while it is failing 500 error on open source code. Is there some thing different between the versions?

https://www.facebook.com/RobertScoble/videos/10153533957779655/

![image](https://cloud.githubusercontent.com/assets/797398/12054044/43c5d478-af45-11e5-9d0c-77d8661844ee.png)

Other FB posts/videos are working. For example:
https://www.facebook.com/FinalWarAgainstCorruption/videos/1062511957147691/ 
![image](https://cloud.githubusercontent.com/assets/797398/12054064/76990460-af45-11e5-8d19-05f31b9bd826.png)

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
FB seems to be having sporadic issues. https://monosnap.com/file/r3BxjValmiMKuvoMo5pfSi2pAySVs3

Some of the servers in our cloud receive error 500 on that URL from FB, some get 200. So I guess our cloud got lucky here to route you to the server that got lucky and received 200 from FB. 

Let's keep monitoring it.

**Comment by iparamonau** [comment]
I am going to close this issue as FB has stabilized that failing URL: it is now constantly returns error code 500 for everyone.
