### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#104]
Hi,

This is a question.I want to know, if the site provides both http:// and https:// url's, then can we get the protocol relative url's, using the open source project?

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
If Iframely sees both http and https version of the embed, it will merge it into one with `//`. 

Is it what you mean?

**Comment by canvas-manik** [comment]
Yes!!!

**Comment by manikmi** [comment]
Actually I checked for vimeo videos, it returned back the thumbnail as http url. 
http://open.iframe.ly/api/oembed?url=https%3A%2F%2Fvimeo.com%2Fondemand%2F28755&origin=preview

**Comment by iparamonau** [comment]
Well in that case Vimeo does not "provide both http:// and https://" for the thumbnail. Just http version. If parsers see both, they will merge it into one that starts with `//`. Vimeo's parser does not look into Twitter card and Open Graph (where thumbnail is https), but only into oembed response. This is to make overall processing faster.
