### ISSUE TITLE
Support for embedding Linkedin.com articles

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#108]
Any plans to add support for embedding linkedin.com articles? Like https://www.linkedin.com/pulse/surprisingly-hard-store-energy-bill-gates?trk=hp-feed-article-title-publish

**Comment by iparamonau** [comment]
Can you point please to where you see the embed codes for this article?

**Comment by manikmi** [comment]
I have seen this working on embed.ly check here:

http://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fwww.linkedin.com%2Fpulse%2Fsurprisingly-hard-store-energy-bill-gates%3Ftrk%3Dhp-feed-article-title-publish 

I see the following json:
{
    "provider_url": "https://www.linkedin.com", 
    "description": "Melinda and I just released our 2016 Annual Letter, in which we discussed two superpowers we wish we had. Melinda wished for more time. I wished for more energy - specifically, cheap, clean energy to help the world's poorest families without contributing to climate change.", 
    "title": "It Is Surprisingly Hard to Store Energy", 
    "url": "https://www.linkedin.com/pulse/surprisingly-hard-store-energy-bill-gates", 
    "thumbnail_width": 698, 
    "thumbnail_url": "https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAASvAAAAJDA5ZTY0ZmUxLTA5YjctNGVlNC1hYjNmLTZjMjFiMWUxNzEwNA.jpg", 
    "author_name": "Bill Gates", 
    "version": "1.0", 
    "provider_name": "LinkedIn Pulse", 
    "type": "link", 
    "thumbnail_height": 400, 
    "author_url": "https://www.linkedin.com/in/williamhgates?trk=pulse-det-athr_prof-art_hdr"
}

**Comment by iparamonau** [comment]
I trust you're referring to http code 999 that you get from LinkedIn. It's a known issue - LinkedIn seem return it to entire Amazon network, and perhaps others. 

[b0fc497](https://github.com/itteco/iframely/commit/b0fc497249d45f51a9369b1d42979ff5f44f9e94)

The above commit have brought an option to route certain regexs via custom HTTP proxies. You'll need to play and find the right fit.
