### ISSUE TITLE
Youtu.be error

### ISSUE THREAD

**Issue by joelabair** [itteco/iframely#110]
Until recently, this was working.  Now every video on youtube returns an error.

-- [16-03-17 18:15:20] Loading /iframely for https://www.youtube.com/watch?v=VbRTxS5sMdA
-- [16-03-17 18:15:22]    -- response (by "youtube.video") 404

**Comment by iparamonau** [comment]
Still works fine. Can you give exact URL and also the version of the Iframely you're using? (should be in package.json)

**Comment by joelabair** [comment]
Sorry for the fire alarm - found the issue.  

Google apparently started ENFORCING that the google API Key has the youtube v3 apis "enabled" in the google developers console.  

I know that this was not even an option in the developer console when I setup the google api key originally.
