### ISSUE TITLE
nytimes video is not returning video url as protocol relative url

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#112]
Hi,
I am trying to embed the following url:
http://nyti.ms/1LL1r04
It returns the html with video embed url as: http://graphics8.nytimes.com/bcvideo/1.0/iframe/embed.html?videoId=100000004255656&amp;playerType=embed 
even though it has ssl url as well
http**s**://graphics8.nytimes.com/bcvideo/1.0/iframe/embed.html?videoId=100000004255656&amp;playerType=embed
Can we get the protocol relative url?

**Comment by iparamonau** [comment]
It was resolved with [this commit](https://github.com/itteco/iframely/commit/8a8898bb943a2ef5878e4cf202c696e2af7316aa)

**Comment by manikmi** [comment]
Thanks Ivan,

I see the fix is there on the Dev branch. Can this be used for our Production build?

Regards,
Manik Mittal

**Comment by manikmi** [comment]
Hi Ivan,
I have tried to take the develop branch code and tried the same url (http://nyti.ms/1LL1r04)there. It returned the following:

{
  "type": "link",
  "version": "1.0",
  "title": "Video: The Terminator and the Washing Machine",
  "author": "RETRO REPORT",
  "provider_name": "NYTimes.com - Video",
  "description": "What the legendary matches between supercomputer Deep Blue and chess grandmaster Garry Kasparov reveal about today’s artificial intelligence and machine learning fears.",
  "thumbnail_url": "http://graphics8.nytimes.com//images/2016/03/06/multimedia/retro-ai/retro-ai-videoSixteenByNine1050.jpg",
  "thumbnail_width": 1050,
  "thumbnail_height": 591,
  "url": "http://www.nytimes.com/video/us/100000004255656/the-terminator-and-the-washing-machine.html"
}

Is there some place where I can check this update?

Regards,
Manik Mittal

**Comment by manikmi** [comment]
Hi Ivan,

I was able to get the work around for this issue. 
The issue is that https://graphics8.nytimes.com/bcvideo/1.0/iframe/embed.html?videoId=100000004255656&amp;playerType=embed is getting redirected to always the url http://graphics8.nytimes.com/video/players/offsite/index.html?videoId=100000004255656&amp%3bplayerType=embed, which is a non-https url, even the source url was https. 

So, i did update the plugins/domains/nytimes.video.js master branch version to update the  href to "https://graphics8.nytimes.com/video/players/offsite/index.html?videoId=" + urlMatch[1] + "&amp%3bplayerType=embed"

Do you see any issue with this approach?

**Comment by iparamonau** [comment]
Great, thanks for reminding why it was http only before. Updated to a new iFrame src. Once they re-publish their oEmbed, we will switch to it again.
