### ISSUE TITLE
Provide example plugin how to return product data

### ISSUE THREAD

**Issue by d-a-n** [itteco/iframely#114]
I can't find any documentation about how to write a plugin that returns product data like price, currency etc.

Please provide a sample plugin or documentation.

**Comment by iparamonau** [comment]
How about [og-product.js](https://github.com/itteco/iframely/blob/master/plugins/meta/og-product.js) and [oembed-product.js](https://github.com/itteco/iframely/blob/master/plugins/meta/oembed-product.js). 

The oembed-product follows the spec that Pinterest consumes in, and data is provided, for example, by any Shopify site.
