### ISSUE TITLE
newsweek embed

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#116]
Hi,

I am not able to get the Embed data for newsweek articles like http://www.newsweek.com/why-does-no-one-care-japanese-are-openly-racist-364129 in the open source code on my server, even though in the view Source for the link it shows og tags. Also, I see it is working on iframely.com. What can be the issue?

**Comment by iparamonau** [comment]
What does the log show?

**Comment by iparamonau** [comment]
The proxy config is available as of v0.9.4. Follow [this example](https://github.com/itteco/iframely/blob/master/config.local.js.SAMPLE#L101)
