### ISSUE TITLE
Add support for CartoDB widgets to iFramely?

### ISSUE THREAD

**Issue by dprophet** [itteco/iframely#117]
Here is a sample URL.

https://bloomberg.cartodb.com/u/eanders/viz/6913f4cc-bd05-11e4-a444-7054d21a95e5/public_map

There is custom metadata thats more map specific that should be parsed via iFramely

**Comment by iparamonau** [comment]
Thanks Erik. I see we miss keywords. Anything else?

**Comment by dprophet** [comment]
@iparamonau Correct. Just the keywords.

**Comment by bshackelton** [comment]
Thank you for the prompt response Ivan, much appreciated.

**Comment by iparamonau** [comment]
`"keywords": "Cruise, Liners, datasets, maps, data visualization, spatial data, geospatial, cartodb"`

The first two come from the title, the rest is boilerplate. Are you sure it is of any use for you?

**Comment by dprophet** [comment]
I just changed the link. 2 most important are 2 metadata items from the header.

<meta property="og:title" content="Cruise Liners 2">

<meta property="og:description" content="My super important description that must show up in iFramely — Map created by eanders in CartoDB">

**Comment by dprophet** [comment]
meta property="og:title"

meta property="og:description"

**Comment by iparamonau** [comment]
It should now be available live for that URL and all new ones. 

For older ones: take into account that we keep meta from the source in the cache for a bit, so if you change it on CartoDB for other URLs it won't necessarily become available via API right away.

**Comment by dprophet** [comment]
Ivan. Thanks. This is working great. My colleague in Bloomberg, Geoff, said you were super helpful and responsive. Glad to see he was 100% correct. Thats rare. Thx again.
