### ISSUE TITLE
Iframely is returning default thumbnail for soundcloud

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#118]
Hi,
This is happening sometimes. I saw a url (https://soundcloud.com/times-the-brief/poll-latino-voters-8216) on soundcloud, which has a meta attribute:
<meta property="og:image" content="https://i1.sndcdn.com/avatars-000144328915-qdcuut-t500x500.jpg">

But if I run it on iframley it returns thumbnail image as:
//a1.sndcdn.com/images/fb_placeholder.png?1461232916

What can be the cause?

Thanks and Regards,
Manik Mittal

**Comment by iparamonau** [comment]
Soundcloud parser works with their oEmbed endpoint only - this is for performance reasons. 

Their oEmbed returns boilerplate image unless user set a custom one for the album. Hence the response. Soundcloud does publish user's avatar in Twitter card and OG, but we're not convinced these edge cases are worth degrading the response time for most of other links. 

We'll think if we can handle such exceptions separately.

**Comment by canvas-manik** [comment]
Thanks a lot Ivan. I explains.

**Comment by iparamonau** [comment]
This should now be resolved in the develop branch
