### ISSUE TITLE
Support for embedding newsweek.com articles

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#121]
Hi,

This is not an issue, but more of a question.
I am trying to embed newsweek.com articles. I added following in the whitelist/iframely-whitelist.json file after theguardian.com

"www.newsweek.com": {
      "date": 1458155428603,
      "og": {
        "photo": "allow"
      }
    },

Did I make any mistake. Also what does this date field mean?

Thanks,
Manik Mittal

**Comment by iparamonau** [comment]
Take a look at the whitelist format as specified here: https://iframely.com/docs/whitelist-format
