### ISSUE TITLE
oEmbed title is cut off with ellipsis at 40chars

### ISSUE THREAD

**Issue by rogeru** [itteco/iframely#129]
Is there a configuration option for the title length returned by the oEmbed API?

**Comment by iparamonau** [comment]
Generally, it shouldn't be the case. Can you give an example URL?

**Comment by rogeru** [comment]
Nevermind, the page defines the title tag with ellipsis.

https://support.ciscospark.com/customer/en/portal/articles/1341983-see-who-is-in-the-room-and-check-for-external-participant
