### ISSUE TITLE
Medium Embed issue

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#131]
While trying to embed a link for https://www.medium.com, I am getting a java script error in Chrome browser console. Although, it is able to generate the embed.

Invalid 'X-Frame-Options' header encountered when loading 'https://api.medium.com/embed?type=story&path=%2Fbetter-people%2Fslack-i-m-breaking-up-with-you-54600ace03ea&id=0&collapsed=null': '' is not a recognized directive. The header will be ignored.

The link which i used was https://medium.com/better-people/slack-i-m-breaking-up-with-you-54600ace03ea#.fo6hfrhrh

Any ideas what can be the issue?

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
It's the issue somewhere on Medium's side and should be reported there. 

Their embeds were broken a while ago because x-frame-options denied embedding. Now it does work, even though with the error in the console.
