### ISSUE TITLE
Docker instructions are wrong?

### ISSUE THREAD

**Issue by sir-gon** [itteco/iframely#132]
First... 

> docker build -t iframely:latest .
> docker run -it -p 8061:8061 -v $PWD/config.local.js:/iframely/config.local.js --name iframely iframely:latest
> docker stop iframely

-v is worng because config.local.js must be a file, but docker uses -v for a volumen DIRECTORY, crashing with:

```
admin@cream ~/iframely> docker run -it -p 8061:8061 -v $PWD/config.local.js:/iframely/config.local.js --name iframely iframely:latest
docker: Error response from daemon: oci runtime error: rootfs_linux.go:53: mounting "/var/lib/docker/devicemapper/mnt/7305f5e6e4a1a06b391ee30fe83bde046e1fbda2883088957d692625e268ba1b/rootfs/iframely/config.local.js" to rootfs "/var/lib/docker/devicemapper/mnt/7305f5e6e4a1a06b391ee30fe83bde046e1fbda2883088957d692625e268ba1b/rootfs" caused "not a directory".

```

second... if i remove -v parameter, and having correct config (tested with "node server" and "pm2" methods), running docker... this time crashes with:

> admin@cream ~/iframely> docker run -it -p 8061:8061 --name iframely iframely:latest
> warn:    --minUptime not set. Defaulting to: 1000ms
> warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
> info:    Forever processing file: cluster.js
> error:   Cannot find forever process: 0
> 

All of this tested with:
* iframely (last table tag: tags/v0.9.7)
* Docker version 1.12.0, build 8eab29e

Can you provide a docker-compose.yml file and/or better tested instructions please?
Meanwhile, I am researching how to create services using docker and systemd.

**Comment by kfei** [comment]
@sir-gon 

First, AFAIK `-v` works fine with single file since a very early version of Docker. [(Doc)](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-file-as-a-data-volume).What's your platform?

Second, the container runs `forever start cluster.js` if no arguments supplied. Can you go into the running container and manually run `forever start cluster.js` to check your configs?

Anyway, the instruction works fine here (Linux 4.4.5/Docker 1.11.0/Iframely 0.9.7). A sample `docker-compose.yml` which I used in my production environment:

```yaml
iframely:
  image: kfei/iframely:develop
  ports:
    - 8061:8061
  volumes:
    - ./iframely/config.local.js:/iframely/config.local.js:ro
  mem_limit: 500M
  restart: always
```

**Comment by iparamonau** [comment]
Thanks @kfei! Closing for now as it seems there is no further issues with it.

**Comment by sir-gon** [comment]
I finally got it working. Was another problem... 

By default, config.local.js has a "host" option with "localhost" value... but in docker... localhost means "this container", and "this container" is working with an IP given by docker host, tipically a "172.X.X.X". Iframely was rejecting all requests. I put "0.0.0.0" in "host" option and works like a charm...

I think the README and config.local.js.SAMPLE comments are not completely accurate about running in docker environment.

**Comment by iparamonau** [comment]
thanks @sir-gon! we'll update the sample config with your comments. Cheers.
