### ISSUE TITLE
using embed.js with opensource iframely

### ISSUE THREAD

**Issue by luizbossoi** [itteco/iframely#133]
Hello

Is that possible to use "embed.js" with this opensource version?
Like this request:

https://iframely.com/embed/http%3A%2F%2Fwww.uol%2Folimpiadas%2Fespeciais%2Fisaquias-queiroz-prata-e-bronze-na-canoagem.htm

And have a "card" for it?

Thanks

**Comment by iparamonau** [comment]
embed.js works only with hosted iFrames, which are not part of the open-source parsers, and so embed.js can not not be used outside of the cloud too.

**Comment by luizbossoi** [comment]
Hello iparamonau, thanks
so in that case the only way to create that kind of "card" is building my own based on iframely API results right?

also i've found possible two bugs,
1. when requesting /debug?uri=http://www.uol/olimpiadas/especiais/isaquias-queiroz-prata-e-bronze-na-canoagem.htm
chrome console log:
Uncaught TypeError: clearData.links.forEach is not a function(anonymous function) @ debug.js:364success @ iframely.js:169c @ jquery.min.js:3fireWith @ jquery.min.js:3k @ jquery.min.js:5r @ jquery.min.js:5
as you can see:
http://192.99.55.23/debug?uri=http://www.uol/olimpiadas/especiais/isaquias-queiroz-prata-e-bronze-na-canoagem.htm

another one with /render method
2. http://192.99.55.23/render?uri=http://www.uol/olimpiadas/especiais/isaquias-queiroz-prata-e-bronze-na-canoagem.htm

on node log I get "undefined"
-- [16-08-18 14:56:43]    -- Using cached meta for: http://www.uol/olimpiadas/especiais/isaquias-queiroz-prata-e-bronze-na-canoagem.htm
undefined


Is that something wrong with my server configuration?
Thanks !

**Comment by iparamonau** [comment]
Yes, building your own is the way to go with self-hosted API. 

The js errors seem to be caused by the cache issues - it looks you have it stored as undefined. Please check you caching engine settings.

**Comment by luizbossoi** [comment]
Hello

Just tested with 'no-cache' flag, issue persists,
CACHE_ENGINE: 'no-cache',
... Using cache engine: no-cache

Error
-- [16-08-18 15:07:55] 201.26.1.91 - Loading /render for http://www.uol/olimpiadas/especiais/isaquias-queiroz-prata-e-bronze-na-canoagem.htm
undefined

Reference:
http://192.99.55.23/render?uri=http://www.uol/olimpiadas/especiais/isaquias-queiroz-prata-e-bronze-na-canoagem.htm

Thanks in advance

**Comment by iparamonau** [comment]
Oh, I see what you mean.  The dev debugger has scripting error - right, we'll fix it. 
To see the response you should try
http://192.99.55.23/iframely?uri=http%3A%2F%2Fwww.uol%2Folimpiadas%2Fespeciais%2Fisaquias-queiroz-prata-e-bronze-na-canoagem.htm

You see there is no html available, and so the /render endpoint does not have anything to work with. This endpoint is meant to use only as fallback for cases when HTML embeds can not be added via JavaScript - it doesn't not generate any widgets itself. You can use the API data and do it yourself.

**Comment by luizbossoi** [comment]
Great Ivan, understood! :+1: 

Thanks!
