### ISSUE TITLE
og:description and twitter:description support

### ISSUE THREAD

**Issue by syuilo** [itteco/iframely#135]
When the `description` meta tag does not exist, check the `og:description` or/and `twitter:description` meta tag.

Sorry my bad English, Thanks for great lib!

**Comment by iparamonau** [comment]
That is exactly how Iframely works. Noticed any issues?

**Comment by syuilo** [comment]
Thanks for reply.
Since the width was narrow, it seems description section has been displayed is omitted.

Sorry!
