### ISSUE TITLE
Iframely open source returns different results 

### ISSUE THREAD

**Issue by billyshena** [itteco/iframely#137]
Hello guys ! 
I have installed iframely open source projet and when I try it like `http://localhost:8061/oembed?url=https://www.google.fr` it returns me a json with some fields.
However, when I use the same query on iframely cloud API `http://iframe.ly/api/iframely?url=http%3A%2F%2Fgoogle.fr&api_key=b0ac0d7ca6a7e9a19f613c` it returns me a json with more fields than what I had in local (missing for example the thumbnail).

Is the iframely cloud api more complete than the open source one?

Best

**Comment by iparamonau** [comment]
Iframely clouds uses the same parsers, so all data should match generally. 

With your particular URL - it indeed doesn't have a thumbnail already, but cloud will keep using stale version for a bit.
