### ISSUE TITLE
returning successful responses on successful calls to iframely (breaking API change)

### ISSUE THREAD

**Issue by iloire** [itteco/iframely#139]
Any thoughts on always returning a successful response to a successful call to _iframely_ no matter how the target host behaved?

At the moment, _iframely_ sort of pipes the error down to the response, so it is difficult to determine whenever it was the target host or _iframely_ itself who failed, and it makes more complicated to create a layer of resilience around the service for consumers.

https://github.com/itteco/iframely/pull/136 helps a bit by providing a JSON response body that can be used for this purpose, but it still feels like a mitigation and not a solution to the root cause. For example, if the target host responds with a 503 error, _iframely_ would return a 500 back to the consumer, indicating that was a server error in _iframely_ itself, when it was not.

My (breaking API) proposal is always return a 200 for a successful processed link, no matter if the target host responded successfully:

```
// status: 200
{
  "preview": {
     "title": "my website",
     ...
  }
}
```

or not:

```
// status: 200
{
  "previewError": {
     "code": 404,
     "message": "http://google.com/badurl couldn't be fetched"
  }
}
```

leaving error status codes in the response itself only for the ones throw by _iframely_ service itself.

Thoughts?

**Comment by iparamonau** [comment]
The approach of returning HTTP errors comes from oEmbed spec, and we have to adhere as people might be migrating legacy integrations. In addition, however, we also return a body with the error description itself. Doesn't it work to detect when there's 500 error on Iframely itself? Also, I think we should just exclude 5xx errors from responses completely and convert it to some 4xx ones. I trust this is already done for the cloud version - we'll port to GitHub too.

**Comment by nleush** [comment]
3c7ea2f6fb02273b1d3ec89564280e84a7d8125a

5xx errors, timeouts and other errors from Iframely core will be proxied as 417.
