### ISSUE TITLE
cached errors don't return as JSON formatted responses

### ISSUE THREAD

**Issue by iloire** [itteco/iframely#141]
``res.tryCacheError`` have its own logic to determine the response for an error, so cached errors won't be returned in JSON format, as per this recent addition:

https://github.com/itteco/iframely/pull/136

**Comment by iloire** [comment]
I'll see if I can submit a PR with the fix and a test over the next week or so.

**Comment by nleush** [comment]
Fixed 376c3fe50538504299d1c56a615f2bb0f2fe885e.
