### ISSUE TITLE
Ability to add custom middleware or routes

### ISSUE THREAD

**Issue by iloire** [itteco/iframely#142]
Story: "As a developer, I would like the ability to have pluggable routes (maybe even middleware), so I can easily extend iframely's core functionality with custom behaviour (like new routes) without having to modify core"

If this is of interest, I can work on a PR. Thanks!

**Comment by iparamonau** [comment]
The best way to handle this story is to plug Iframely in as a library. This way you can build all the routes you want on top. It would the easiest way for you to maintain extensions too.  

We try and keep Iframely here to its core parsing purpose. Extra features would expose it to scope creep. Any reason why you can't use the library?

**Comment by iloire** [comment]
https://github.com/itteco/iframely/pull/145 also takes care of this feature request because, by extracting out ``app.js`` into a separate file, you will be able now to use your own ``server.js`` file that requires ``app.js`` and adds your custom routes.

**Comment by iparamonau** [comment]
Guess we'll close this one too since #145 is merged. Pls re-open if still needed. Cheers
