### ISSUE TITLE
Wrong Canonical URL

### ISSUE THREAD

**Issue by suvozit** [itteco/iframely#147]
URL: https://youtu.be/dOMsI7p_HQ4
Effective: https://www.youtube.com/watch?v=dOMsI7p_HQ4&feature=youtu.be
Canonical: https://www.youtube.com/watch?v=dOMsI7p_HQ4

# Response
```json
// 20161228121018
// http://open.iframe.ly/api/iframely?url=https%3A%2F%2Fyoutu.be%2FdOMsI7p_HQ4&origin=preview

{
  "url": "https://youtu.be/dOMsI7p_HQ4",
  "meta": {
    "canonical": "https://youtu.be/dOMsI7p_HQ4",
    "site": "YouTube",
```

**Comment by iparamonau** [comment]
Thanks, we'll fix it in v 1.0.2

**Comment by suvozit** [comment]
@iparamonau When is the expected release date?

**Comment by iparamonau** [comment]
We seem to be on a monthly release schedule, so most likely in 2-3 weeks

**Comment by suvozit** [comment]
That's awesome!
