### ISSUE TITLE
Missing media.width,height in links.thumbnail

### ISSUE THREAD

**Issue by suvozit** [itteco/iframely#149]
# As Iframely API
```json
// 20161230102041
// http://iframe.ly/api/iframely?url=http%3A%2F%2Ffiredrop.ai&api_key=XXX

{
  "url": "http://firedrop.ai",
  "meta": {
    "canonical": "https://firedrop.ai/",
    "theme-color": "#da532c",
    "keywords": "firedrop, A.I., web design, webdesign, artificial intelligence",
    "description": "Firedrop uses artificial intelligence to design a website automatically around your content in less than 60 seconds. No more templates, no more web designers, just your own unique site in minutes.",
    "site": "Firedrop",
    "title": "Firedrop - websites that build themselves using artificial intelligence"
  },
  "links": {
    "thumbnail": [
      {
        "rel": [
          "thumbnail",
          "ssl"
        ],
        "type": "image/png",
        "href": "https://firedrop.ai/img/og-fb-image-sq-2.png"
      }
    ],
```

# As oEmbed API
missing `thumbnail_width,height`

```json
// 20161230102950
// http://iframe.ly/api/oembed?url=http%3A%2F%2Ffiredrop.ai&api_key=XXX

{
  "url": "https://firedrop.ai/",
  "type": "rich",
  "version": "1.0",
  "title": "Firedrop - websites that build themselves using artificial intelligence",
  "provider_name": "Firedrop",
  "description": "Firedrop uses artificial intelligence to design a website automatically around your content in less than 60 seconds. No more templates, no more web designers, just your own unique site in minutes.",
  "thumbnail_url": "https://firedrop.ai/img/og-fb-image-sq-2.png",
  "cache_age": 86400,
  "html": "<a href=\"https://firedrop.ai/\" data-iframely-url=\"//cdn.iframe.ly/api/iframe?url=http%3A%2F%2Ffiredrop.ai&key=XXX\"></a><script async src=\"//cdn.iframe.ly/embed.js\" charset=\"utf-8\"></script>"
}
```

**Comment by iparamonau** [comment]
the detection of image sizes is in place and works well if origin server is responding well. There could be a connection issue, for example it took too long to get the image headers. It would not be feasible to debug what happened in that particular case. Generally, it works as expected.

**Comment by suvozit** [comment]
ooh, ok!

But in that case cant you *must send* `thumbnail_url` as NULL. Because `thumbnail_url` is optional.

> **`thumbnail_url`** (optional)
> A URL to a thumbnail image representing the resource. The thumbnail must respect any `maxwidth` and `maxheight` parameters. If this parameter is present, `thumbnail_width` and `thumbnail_height` *must also be present*.
>
> **`thumbnail_width`** (optional)
> The width of the optional thumbnail. If this parameter is present, `thumbnail_url` and `thumbnail_height` *must also be present*.
>
> **`thumbnail_height`** (optional)
> The height of the optional thumbnail. If this parameter is present, `thumbnail_url` and `thumbnail_width` *must also be present*.
> 
> &mdash; http://oembed.com/
