### ISSUE TITLE
iframely returns different responses for the same content

### ISSUE THREAD

**Issue by tombburnell** [itteco/iframely#150]
/oembed?url=https://twitter.com/TheOnion/status/793466639480160256

sometimes I get the first block, sometimes I get the second block.

{
"type": "rich",
"version": "1.0",
"title": "The Onion on Twitter",
"author": "The Onion",
"author_url": "https://twitter.com/TheOnion",
"provider_name": "Twitter",
**"description": "“Editorial Cartoon: 'United We Grand' https://t.co/G6uZA4DhdO”",**
"thumbnail_url": "https://pbs.twimg.com/media/CwL1s66WIAAF6tL.jpg:large",
"**width": 550,
"**html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Editorial Cartoon: &#39;United We Grand&#39; <a href=\"https://t.co/G6uZA4DhdO\">https://t.co/G6uZA4DhdO</a> <a href=\"https://t.co/7ulxmXRT7W\">pic.twitter.com/7ulxmXRT7W</a></p>&mdash; The Onion (@TheOnion) <a href=\"https://twitter.com/TheOnion/status/793466639480160256\">November 1, 2016</a></blockquote>\n<script async src=\"//platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"
}

{
"type": "rich",
"version": "1.0",
"title": "The Onion on Twitter",
"author": "The Onion",
"author_url": "https://twitter.com/TheOnion",
"provider_name": "Twitter",
"thumbnail_url": "https://pbs.twimg.com/media/CwL1s66WIAAF6tL.jpg:large",
**"thumbnail_width": 1200,
"thumbnail_height": 675,**
"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Editorial Cartoon: &#39;United We Grand&#39; <a href=\"https://t.co/G6uZA4DhdO\">https://t.co/G6uZA4DhdO</a> <a href=\"https://t.co/7ulxmXRT7W\">pic.twitter.com/7ulxmXRT7W</a></p>&mdash; The Onion (@TheOnion) <a href=\"https://twitter.com/TheOnion/status/793466639480160256\">November 1, 2016</a></blockquote>\n<script async src=\"//platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"
}

**Comment by iparamonau** [comment]
By the looks of it, one response was generated via specific Twitter domain plugin, while the second comes from generic oEmbed parser. 

You either changed the settings in the config between the requests, or Twitter was responding differently to your server, which made the domain plugin to fall back to generic parser.

**Comment by suvozit** [comment]
@iparamonau How is it possible that same `thumbnail_url` results in missing `thumbnail_width`, `thumbnail_height`

**#149 Missing media.width,height in links.thumbnail**

> the detection of image sizes is in place and works well if origin server is responding well. There could be a connection issue, for example it took too long to get the image headers. It would not be feasible to debug what happened in that particular case. Generally, it works as expected.
> &mdash; @iparamonau

> In that case you *must send* `thumbnail_url` as NULL because `thumbnail_url` is optional
> &mdash; @suvozit

> **`thumbnail_url`** (optional)
> A URL to a thumbnail image representing the resource. The thumbnail must respect any `maxwidth` and `maxheight` parameters. If this parameter is present, `thumbnail_width` and `thumbnail_height` *must also be present*.
>
> **`thumbnail_width`** (optional)
> The width of the optional thumbnail. If this parameter is present, `thumbnail_url` and `thumbnail_height` *must also be present*.
>
> **`thumbnail_height`** (optional)
> The height of the optional thumbnail. If this parameter is present, `thumbnail_url` and `thumbnail_width` *must also be present*.
> 
> &mdash; oEmbed http://oembed.com/

**Comment by iparamonau** [comment]
Twitter parser has been modified to always return images (except when thumbnail=avatar). Will be available with the next release of self-hosted version or in the cloud right away.
