### ISSUE TITLE
Iframely videos embedded into iframe can inherit margin from parents

### ISSUE THREAD

**Issue by pmd-bgermain** [itteco/iframely#153]
When you embed a video with iframely you have a html code like this :

`<div><div style="width: 100%; height: 0px; position: relative; padding-bottom: 75.0019%;"><iframe src="https://www.youtube.com/embed/OqbwyJy5xrk?wmode=transparent&rel=0&autohide=1&showinfo=0&enablejsapi=1" frameborder="0" allowfullscreen style="width: 100%; height: 100%; position: absolute;"></iframe></div></div>`

It can be an issue when your document already have iframes that are styled with margins, a simple solution is to add a margin 0 to the inner iframe on witch is applied the responsive keep ratio technique.

You should have something like this :
`<div><div style="width: 100%; height: 0px; position: relative; padding-bottom: 75.0019%;"><iframe src="https://www.youtube.com/embed/OqbwyJy5xrk?wmode=transparent&rel=0&autohide=1&showinfo=0&enablejsapi=1" frameborder="0" allowfullscreen style="width: 100%; height: 100%; position: absolute;margin:0"></iframe></div></div>`

What do you think about adding this in your code ?

**Comment by iparamonau** [comment]
Can't you just wrap the embed code into a div with a class name and then exclude styles of iFrames within that class with margin:0 ?

**Comment by pmd-bgermain** [comment]
I could if I had the power over the code inserted in my page but I have not.

I have this iframely code embedded into an article body generated with a wysiwyg editor. I can style the code html of my articles on each website using generic selector like iframe, p, ... but iframe can be wrapped with a div or not and may or may not have margins ... I can't really master when I will have a case or another without the context and as you mentionned it I could have a class on the div wrapping the responsive iframe but I don't have it :(.
Moreover I have 20 sites using this wysiwyg editor and I won't have to edit all of the sites using the wysiwyg but only the backoffice one ... 

So I thought that the simplest solution was to add a margin 0 on the responsive iframes because it can't break anything (it will secure the rendering of it) and all I have to do is to update my editor using iframely as a part of the html renderer and I am ready to go.

**Comment by iparamonau** [comment]
It will be resolved with the upcoming [&omit_css](https://iframely.com/docs/omit-css) parameter. Self-hosted will have it in next release, the embeds will start being wrapped into `iframely-embed` class which you can customize.
