### ISSUE TITLE
Self-host Iframely on AWS Elasticbeanstalk

### ISSUE THREAD

**Issue by suvozit** [itteco/iframely#154]
I tried installing Iframely on AWS Elasticbeanstalk

with the following configuration:
```js
// config.local.js
baseAppUrl: "http://lowcost-env.wbu5hrwnbu.us-west-2.elasticbeanstalk.com",
CACHE_ENGINE: 'no-cache',
```
![screen shot 2017-02-21 at 9 30 39 pm](https://cloud.githubusercontent.com/assets/5635088/23173587/a884d100-f87f-11e6-9059-e4998081b127.png)
http://lowcost-env.wbu5hrwnbu.us-west-2.elasticbeanstalk.com

**Comment by iparamonau** [comment]
It looks NGINX doesn't have the connection to Iframely. Make sure NGINX config is correct and can connect to the port on which Iframely is running.

**Comment by suvozit** [comment]
Its working!

![screen shot 2017-02-24 at 1 27 27 pm 2](https://cloud.githubusercontent.com/assets/5635088/23295308/d8249ba8-fa95-11e6-9b86-49fbb9632707.png)
