### ISSUE TITLE
Error responses in self-hosted version

### ISSUE THREAD

**Issue by suvozit** [itteco/iframely#158]
But working with iframely.com

# 417

https://tmblr.co/Za2Ncx2IpyW00

```json
{
  "error": {
    "source": "iframely",
    "code": 417,
    "message": "Unsupported Media Type"
  }
}
```

# 408

http://bit.ly/1ObG5EX
http://ti.me/1JN6eMR
http://www.benjerry.co.uk/whats-new/2017/02/bob-marley
http://texmage.com/texmages/582ab01637d6b6cd258b4567
http://bobmarley.com/marley70-a-retrospective
http://labs.tffchallenge.com/posts/text/detail/1118/#.WFaY5kdeUrg.twitter

```json
{
  "error": {
    "source": "iframely",
    "code": 408,
    "message": "Timeout"
  }
}
```

I am using 60sec timeout from Guzzle, PHP HTTP client

**Comment by suvozit** [comment]
I believe I have to use tumblr key

```json
tumblr: {
    consumer_key: "INSERT YOUR VALUE"
    // media_only: true     // disables status embeds for images and videos - will return plain media
},
```

and increase the timeout

```json
// If there's no response from remote server, the timeout will occur after
RESPONSE_TIMEOUT: 5 * 1000, //ms
```

what is the timeout I shall use for best results?

**Comment by iparamonau** [comment]
Depends on what is the best result for you. 5 secs is reasonable timeout default not to clog the network interface with pending connections. If you have fewer connections, you may want to give origin servers a bit more time.

**Comment by suvozit** [comment]
URL: http://pco.lt/1W7nZck
```
504 Gateway Time-out
```

http://open.iframe.ly/api/iframely?url=http%3A%2F%2Fpco.lt%2F1W7nZck&origin=preview
```
// 20170314235732
// http://open.iframe.ly/api/iframely?url=http%3A%2F%2Fpco.lt%2F1W7nZck&origin=preview

{
  "url": "http://pco.lt/1W7nZck",
  "meta": {
    "media": "player",
    "canonical": "https://blog.soundcloud.com/2016/01/13/announcing-our-partnership-with-universal-music-group/#prclt-5520vXx3",
    "author_url": "https://blog.soundcloud.com/author/alex/",
    "author": "Alex",
    "site": "SoundCloud",
    "title": "Announcing Our Partnership with Universal Music Group"
  },
```
