### ISSUE TITLE
Return a larger icon on Facebook posts

### ISSUE THREAD

**Issue by GromNaN** [itteco/iframely#159]
On [Twitter URLs](https://iframely.com/embed/https%3A%2F%2Ftwitter.com%2FTeleLoisirs%2Fstatus%2F839046743669026816), a [large icon of Twitter](https://abs.twimg.com/icons/apple-touch-icon-192x192.png) is returned.

Is it possible to return [a similarly large icon](https://www.facebook.com/images/fb_icon_325x325.png) on [Facebook posts](https://iframely.com/embed/https%3A%2F%2Fwww.facebook.com%2Fbeast.the.dog%2Fphotos%2Fa.202825176411010.62662.202825023077692%2F1321470941213089%2F%3Ftype%3D3) ?

This icon comes from the Facebook homepage:
```
<meta property="og:image" content="https://www.facebook.com/images/fb_icon_325x325.png" />
```

**Comment by iparamonau** [comment]
Doing so would require a hardcode, which we'd rather not do for Facebook. 

But you may have your own plugin to add it. 

See `CUSTOM_PLUGINS: __dirname + '/yourcustom-plugin-folder'` in config example - that would be your custom plugins folders. You may add it to gitignore

Simple plugin that hardcodes the icon: https://gist.github.com/iparamonau/416f5c66f3315c88536f208aee3bbef2
