### ISSUE TITLE
use proxy from config when loading white list

### ISSUE THREAD

**Issue by drewlloyd** [itteco/iframely#163]
A typical corporate environment uses proxy servers such as the open source squid to access the internet.

In such an environment iframely returns the following error.

data:    cluster.js:26 - Error loading whitelist from http://iframely.com/qa/whitelist.json : Error: getaddrinfo ENOTFOUND iframely.com iframely.com:80

The root cause of this error is that lib/whitelist.js function loadWhitelistUrl() directly calls the request module.

There are two solutions I can think of:
1. use the iframely request wrapper module
2. use utils.prepareRequestOptions() 

I guess loadWhitelistUrl doesn't use the wrapper module because its a special case that should not be cached.

#160 chooses utils.prepareRequestOptions() which only adds proxy (and user agent) options to the request.

**Comment by iparamonau** [comment]
Thanks, the approach in #160 is perfect. We'll merge for the release. 

Closing this for now, thanks for the additional info!
