### ISSUE TITLE
Iframely language setting

### ISSUE THREAD

**Issue by billyshena** [itteco/iframely#169]
Hi everyone,

I am currently using iframely on a EC2 based in Francfort (Germany) and the results returned are directly translated into the language of the server (metadata will be in Deutsch for this case)

Is there any way to configure the i18n default setting ?

Best,

**Comment by iparamonau** [comment]
You probably mean some specific providers that check by IP address. Need to know which provider it is.

If that is for FB, you may configure it in your provider options (see sample config) as 

```
facebook: {
                language_code: 'en_US'  
```

**Comment by billyshena** [comment]
Yes, if I try to put http://facebook.com or http://google.com, it will display all the results in the language where the iframely server is hosted

Should I add the 'language_code' parameter for each provider ?
Is there a way to globally set that ?

Best,

**Comment by iparamonau** [comment]
There's no setting for google at the moment. We'd have to come up with a generic solution here. 

For FB embeds - it's fairly simple via `language_code`. Probably won't work on the root facebook.com url though.

**Comment by billyshena** [comment]
Mhh I see, so I'm thinking of two solutions:

- Host my iframely server somewhere else
- Use a proxy server 

Currently I would like to display all the information returned in French so I would host the server in France to fix that issue for the moment ?

**Comment by iparamonau** [comment]
It's difficult for us to test French/German issues, but if since you do, please run a little test by adding 

`Accept-Language` : 'fr-FR, fr;q=0.9, en;q=0.8, *;q=0.5'

to the request headers on this line:
https://github.com/itteco/iframely/blob/develop/lib/utils.js#L76

If that works, we'll include that option into the general config.

**Comment by billyshena** [comment]
It works using the "Accept-Language" header 👍 
Thanks for your support @iparamonau

**Comment by iparamonau** [comment]
It is now resolved in the `develop` branch. The config option is `locale` in `providerOptions`.
