### ISSUE TITLE
Pinterest international plugin causes redirect loop

### ISSUE THREAD

**Issue by tbasse** [itteco/iframely#171]
When requesting data from the `/iframely` endpoint for Pinterest pages iFramely ends up in a redirect-loop.

```
-- Loading /iframely for https://pinterest.com/pin/392868767485074253/
-- plugin redirect (by "htmlparser") https://www.pinterest.com/pin/392868767485074253/
-- plugin redirect (by "htmlparser") https://au.pinterest.com/pin/392868767485074253/
-- plugin redirect (by "pinterest.international") https://www.pinterest.com/pin/392868767485074253/
-- plugin redirect (by "htmlparser") https://au.pinterest.com/pin/392868767485074253/
-- plugin redirect (by "pinterest.international") https://www.pinterest.com/pin/392868767485074253/
Requested page error: redirect loop
```

Pinterest itself is redirecting the requested URL to the local `au.pinterest.com` domain which then is redirected by the [pinterest.international.js](https://github.com/itteco/iframely/blob/master/plugins/domains/pinterest.com/pinterest.international.js) plugin to the international domain again, and so on and so on until it hits the MAX_REDIRECTS limit.

**Comment by tbasse** [comment]
Oh, and just out of curiosity: What was/is the benefit of iFramely redirecting to the international domain when a local domain was requested? :)

**Comment by iparamonau** [comment]
The redirect loop should be fixed now. The redirect itself is more for future-proofing and streamlining the processing logic for alternative URLs like https://www.pinterest.com/pin/AVrCsLXrlVATjdkqI-KuNc6SnXr3aVTnuxoVrXzJHtphdBTjtymDkS4/
