### ISSUE TITLE
no amp embed with parameter &iframe=amp

### ISSUE THREAD

**Issue by linuz43** [itteco/iframely#173]
it seems that the opensource version of iframely not generate amp version of embeds. Is this a bug or a feature that is not in the opensource version?
hosted version give amp embed code back:
`http://open.iframe.ly/api/iframely?url=https%3A%2F%2Fwww.facebook.com%2FPolizeiBerlin%2Fposts%2F706855522831888&origin=explore&iframe=amp

...
"html": "<amp-facebook width=\"400\" height=\"400\" layout=\"responsive\" data-href=\"https://www.facebook.com/PolizeiBerlin/posts/706855522831888\"></amp-facebook>"`

self hosted version don't react to url parameter
`http://our-iframely.service/iframely?url=https%3A%2F%2Fwww.facebook.com%2FPolizeiBerlin%2Fposts%2F706855522831888&iframe=amp

...
"html": "<div class=\"fb-post\" data-href=\"https://www.facebook.com/PolizeiBerlin/posts/706855522831888?iframe=amp\" data-width=\"640\"><blockquote cite=\"https://www.facebook.com/PolizeiBerlin/posts/706855522831888\" class=\"fb-xfbml-parse-ignore\"><p>+++ #Transformers ben&#xf6;tigen ein Update +++\n\nDa haben #Bumblebee und #Barricade die Rechnung wohl ohne unsere stahlharten...</p>Posted by <a href=\"https://www.facebook.com/PolizeiBerlin/\">Polizei Berlin</a> on&nbsp;<a href=\"https://www.facebook.com/PolizeiBerlin/posts/706855522831888\">Freitag, 16. Juni 2017</a></blockquote></div>"`

**Comment by iparamonau** [comment]
It's not just this - self-hosted version is the parsers only, it does not include most of iFrame features.
