### ISSUE TITLE
Self-hosted Iframely: No image sizes in media object returned

### ISSUE THREAD

**Issue by gregor76** [itteco/iframely#174]
Hi,

in the JSON responses for API requests using our self-hosted Iframely version the media object query attributes width and height for images/thumbnails are missing, independent of the provider.

Is this feature not supported in the self-hosted version? Or is there a general config option for the media attributes?

Thanks,
Greg

**Comment by iparamonau** [comment]
There are two parameters in the default config that you need to change. See config.providerOptions section in your `config.local.js`

            images: {
                loadSize: false, // if true, will try an load first bytes of all images to get/confirm the sizes
                checkFavicon: false // if true, will verify all favicons
            },

**Comment by iparamonau** [comment]
Assuming the issue is now resolved.
