### ISSUE TITLE
Pinterest image not showing up 

### ISSUE THREAD

**Issue by sayedatif** [itteco/iframely#176]
I am using iframely in my angular project. Everything was working fine until i tried pinterest image link. for other site example dribble.com, 500px.com etc its working fine. Basically pinterest images shows up on first time but when i perform any action or any transition between routes it hides.

**HTML for pinterest images:**
`<a data-pin-do="embedPin" href="https://www.pinterest.com/pin/355362226820761414/" data-pin-width="large" ></a><script async defer type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>`

**HTML for other links:**
```
<a href="https://www.facebook.com/" data-iframely-url="//cdn.iframe.ly/api/iframe?url=http%3A%2F%2Fwww.facebook.com&key=155c6006ee6df99ff4c5bf3a68ef7a73"></a><script async src="//cdn.iframe.ly/embed.js" charset="utf-8"></script>

<a href="https://500px.com/photo/160435221/p-o-n-y-http-bit-ly-28zapzc-by-kevin-biberbach" data-iframely-url="//cdn.iframe.ly/api/iframe?url=https%3A%2F%2F500px.com%2Fphoto%2F160435221%2Fp-o-n-y-http-bit-ly-28zapzc-by-kevin-biberbach&key=155c6006ee6df99ff4c5bf3a68ef7a73"></a><script async src="//cdn.iframe.ly/embed.js" charset="utf-8"></script>
```

Other sites HTML works well even after transitions or operation performed across app. is it the issue with pinterest images or i am doing some thing wrong??

**Comment by iparamonau** [comment]
You should try the API calls with &iframe=1, or change it in your API settings. There is a little thing we should tweak for Pinterest indeed, but regardless of it, if you use Angular, we recommend &iframe=1 as API parameter (or change it in your settings). 

If the problem persists - please reach us out at support@iframely.com. That's a better support channel for our cloud version.

**Comment by sayedatif** [comment]
thanks  @iparamonau  it worked
