### ISSUE TITLE
facebook video data not extracted

### ISSUE THREAD

**Issue by sirpy** [itteco/iframely#179]
this linke isn't being extracted on the opensource version, on iframely site it seems fine
https://www.facebook.com/TED/videos/10159289224535652/

**Comment by iparamonau** [comment]
It may be not shown in /debug if you have `SKIP_IFRAMELY_RENDERS: true` in your config. But actual API calls return it as `html` field.

**Comment by sirpy** [comment]
what i mean is that it should be found as video, that's what facebook oembed endpoint returns.
i've tried setting skip renders to false but same result.
the above video is identified as rich and not as video.
```
{"type":"rich","version":"1.0","title":"How to find your purpose and become a great leader","author":"TED","author_url":"https://www.facebook.com/TED/","provider_name":"Facebook","description":"Want to feel inspired at work? Discover what drives you with author and optimist Simon Sinek. Ask him your questions in the comments!","thumbnail_url":"https://scontent.fsdv3-1.fna.fbcdn.net/v/t15.0-10/21370501_10159289383870652_1543348115011010560_n.jpg?oh=23463d1d803bb82d7a4314629cb846ac&oe=5A53BD36","html":"<div class=\"fb-video\" data-href=\"https://www.facebook.com/TED/videos/10159289224535652/\"><blockquote cite=\"https://www.facebook.com/TED/videos/10159289224535652/\" class=\"fb-xfbml-parse-ignore\"><a href=\"https://www.facebook.com/TED/videos/10159289224535652/\">How to find your purpose and become a great leader</a><p>Want to feel inspired at work? Discover what drives you with author and optimist Simon Sinek. Ask him your questions in the comments!</p>‎Posted by <a href=\"https://www.facebook.com/TED/\">TED</a> on‎ יום רביעי 6 ספטמבר 2017</blockquote></div>"}
```

**Comment by sirpy** [comment]
i'm not using /debug... actually now that i've tried /debug i can't seem to get /debug to work. it doesnt seem to do anyhing. (i dont see anything on the server output when i enter a url to debug)

**Comment by sirpy** [comment]
are there any specific settings  i need to enable/set to get similar results to iframely.com?

after some further debugging, i see that the facebook.video plugin runs, and the oembed result in the oemebd plugin has type=video
i also see that the server prints
-- fallback from domain to generic { 'facebook.com': true }

in the recursive call to run the plugins the method resultsHasDomainData does get the result from the facebook.video
but the final allResults variable doesnt have it.

don't really know what to make out of it...

**Comment by nleush** [comment]
Must be fixed now in `develop`.

**Comment by sirpy** [comment]
thanks seems ok now
