### ISSUE TITLE
Amazon iframely doesn't work properly on the self hosted version

### ISSUE THREAD

**Issue by dangerusslee** [itteco/iframely#182]
That is what comes back in the self hosted version.  

`{"meta":{"title":"Amazon.com: All-new Echo (2nd Generation) with improved sound, powered by Dolby, and a new design – Charcoal Fabric: Amazon Devices","keywords":"All-new Echo (2nd Generation) with improved sound, powered by Dolby, and a new design – Charcoal Fabric,Amazon,XC56PY","canonical":"https://www.amazon.com/all-new-amazon-echo-speaker-with-wifi-alexa-dark-charcoal/dp/B06XCM9LJ4"},"links":{"icon":[{"href":"https://www.amazon.com/favicon.ico","type":"image/icon","rel":["icon","ssl"]}]},"rel":[]}`

This is what comes back from the online version for the same url:

`{
    "id": "PIYLxmC",
    "url": "https://www.amazon.com/dp/B06XCM9LJ4",
    "meta": {
        "site": "Amazon.com",
        "canonical": "https://www.amazon.com/all-new-amazon-echo-speaker-with-wifi-alexa-dark-charcoal/dp/B06XCM9LJ4",
        "description": "Amazon.com: All-new Echo (2nd Generation) with improved sound, powered by Dolby, and a new design – Charcoal Fabric: Amazon Devices",
        "keywords": "All-new Echo (2nd Generation) with improved sound, powered by Dolby, and a new design – Charcoal Fabric,Amazon,XC56PY",
        "title": "All-new Echo (2nd Generation) with improved sound, powered by Dolby, and a new design - Charcoal Fabric"
    },
    "links": {
        "thumbnail": [
            {
                "content_length": 15347,
                "media": {
                    "height": 315,
                    "width": 600
                },
                "rel": [
                    "thumbnail",
                    "og",
                    "ssl"
                ],
                "type": "image/jpeg",
                "href": "https://images-na.ssl-images-amazon.com/images/I/51TFnR7AtGL._SR600%2c315_PIWhiteStrip%2cBottomLeft%2c0%2c35_PIAmznPrime%2cBottomLeft%2c0%2c-5_SCLZZZZZZZ_.jpg"
            }
        ],
        "icon": [
            {
                "rel": [
                    "icon",
                    "ssl"
                ],
                "type": "image/icon",
                "href": "https://www.amazon.com/favicon.ico"
            }
        ]
    },
    "rel": [
        "summary",
        "ssl",
        "html5",
        "inline"
    ],
    "html": "<a href=\"https://www.amazon.com/all-new-amazon-echo-speaker-with-wifi-alexa-dark-charcoal/dp/B06XCM9LJ4\" data-iframely-url=\"//cdn.iframe.ly/PIYLxmC\"></a><script async src=\"//cdn.iframe.ly/embed.js\" charset=\"utf-8\"></script>"
}`

**Comment by iparamonau** [comment]
Self-hosted and cloud versions are not necessarily identical. Though we use the same parsers in the cloud, [readme](https://github.com/itteco/iframely#not-included-as-compared-to-cloud-api) mentions that there are features that are not included.
