### ISSUE TITLE
Problem with twitch

### ISSUE THREAD

**Issue by fraitag** [itteco/iframely#183]
Hi, 
twitch changed domain twitch.com to sub-domain go.twitch.com . Current iframely not support new URLS. I saw changes in develop branch but still wait to prepare PR.

**Comment by iparamonau** [comment]
Thanks. Twitch should work via generic whitelist, our plugin just adds couple options that we need for the cloud. Anyway, we'll push it to master later this week.

**Comment by iparamonau** [comment]
This is now pushed to master & npm as v 1.2.1
