### ISSUE TITLE
Not processing some amazon URLs

### ISSUE THREAD

**Issue by dangerusslee** [itteco/iframely#185]
-- [17-11-15 01:54:42] 71.127.208.231 - Loading /iframely for https://www.amazon                                                                                                             .com/dp/B01ERZEYK0/
-- [17-11-15 01:54:42]    -- response (by "htmlparser") 503
HttpError: Requested page error: 503
    at handleIframelyError (/tank/iframely/modules/api/views.js:61:18)
    at /tank/iframely/modules/api/views.js:125:24
    at /tank/iframely/node_modules/async/dist/async.js:421:16
    at next (/tank/iframely/node_modules/async/dist/async.js:5278:29)
    at /tank/iframely/node_modules/async/dist/async.js:906:16
    at asyncMethodCb (/tank/iframely/lib/core.js:1506:32)
    at /tank/iframely/lib/core.js:269:29
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by iparamonau** [comment]
`response (by "htmlparser") 503` means that the origin server responded with HTTP status code 503. Do you have a line break in the URL?

**Comment by dangerusslee** [comment]
No, no linebreak.

**Comment by dangerusslee** [comment]
Seems like I am getting 503 just trying to wget amazon from that box:

# wget "http://www.amazon.com/"
--2017-11-15 03:24:12--  http://www.amazon.com/
Resolving www.amazon.com (www.amazon.com)... 104.86.87.164
Connecting to www.amazon.com (www.amazon.com)|104.86.87.164|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.amazon.com/ [following]
--2017-11-15 03:24:12--  https://www.amazon.com/
Connecting to www.amazon.com (www.amazon.com)|104.86.87.164|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2017-11-15 03:24:12 ERROR 503: Service Unavailable.


Looks like some kind of block.  Any ideas?

**Comment by iparamonau** [comment]
Sorry, 503 errors are beyond our control. But you should be wget'ting `https://www.amazon.com/dp/B01ERZEYK0/` - that's why I mentioned the line break in the URL.

**Comment by dangerusslee** [comment]
None of the amazon URLs work even with wget.  Either they're having service issues, or are blocking my IP due to too many requests.  

I don't believe my traffic is that high.  I assume you guys hit the amazon site a lot, have you ever gotten blocked with 503s?

**Comment by iparamonau** [comment]
They may have blocked wget itself. The URL is still invalid in the issue's log as it has the line break in it. 

We do get occasional robots checks on amazon, but not 503s.

**Comment by dangerusslee** [comment]
tried lynx and I am getting the botcheck.  Is there a fix?

Enter the characters you see below

   Sorry, we just need to make sure you're not a robot. For best results, please make sure your browser is accepting cookies.

Type the characters you see in this image:

   [Captcha_hytvaicgxq.jpg]
   Try different image
   ____________________
   (BUTTON) Continue shopping
   Conditions of Use Privacy Policy
   © 1996-2014, Amazon.com, Inc. or its affiliates [requestId=9AK2QQYZ9EFGRSCME9RK&js=0]
