### ISSUE TITLE
Wrong url retrieved through oEmbed

### ISSUE THREAD

**Issue by ZissisT** [itteco/iframely#187]
Hello,

When  trying to use oEmbed method to fetch preview for 
http://www.bbc.com/news

the resulting object is

{
    "id": "qvU3ZJt",
    **"url": "http://www.bbc.com/www.bbc.co.uk/news",**
    "type": "rich",
    "version": "1.0",
    "title": "Home - BBC News",
    "author_url": "https://www.facebook.com/bbcnews",
    "provider_name": "BBC News",
    "description": "Visit BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news.",
    "thumbnail_url": "//m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/2.0.0/bbc_news_logo.png",
    "thumbnail_width": 1024,
    "thumbnail_height": 576,
    "cache_age": 86400,
    "html": "<div class=\"iframely-embed\" style=\"max-width: 2048px;\"><div class=\"iframely-responsive\"><a **href=\"http://www.bbc.com/www.bbc.co.uk/news\"** data-iframely-url=\"//cdn.iframe.ly/qvU3ZJt\"></a></div></div><script async src=\"//cdn.iframe.ly/embed.js\" charset=\"utf-8\"></script>"
}

This breaks any usage of the URL returned.
This can be reproduced in https://iframely.com/embed/http%3A%2F%2Fwww.bbc.com%2Fnews

Is that because of the API or because of wrong meta data in www.bbc.com ?

**Comment by iparamonau** [comment]
The URL retrieved is the correct one. 

The `"canonical": "http://www.bbc.com/www.bbc.co.uk/news"`
is what converts into URL field in oembed response. It is just a data field and does not affect the card created - the link inside the card is the original one, not a canonical.

**Comment by ZissisT** [comment]
@iparamonau That is not true, you are checking the generated html in iframely site, the html returned by the API has href="http://www.bbc.com/www.bbc.co.uk/news\"   which is wrong. I posted the response of the API above, which returns to the user wrong URL and wrong embedded HTML, so they can not use it in any way

**Comment by iparamonau** [comment]
In 
`<a href="http://www.bbc.com/www.bbc.co.uk/news\" data-iframely-url="//cdn.iframe.ly/qvU3ZJt">`, 
the `href` is irrelevant for the code that renders a card. The script considers only `data-iframely-url`, href can be anything. 

For users, they simply won't see that `<a>` as first it's empty, and then it's a card when it is rendered. So, not UX issues there as well. 

Am I missing anything?

**Comment by ZissisT** [comment]
No, you are not I guess,
The issue is because in our app, which we use iFramely in, we don't use the returned html directly but rather build our own html based on the api response data. And we use the returned URL for this. We will try and use the given URL before api request so we don't fall in same case again.

Thank you
Zissis

**Comment by iparamonau** [comment]
Yes, the original URL is safer in that case, as Iframely would expand all URL shorteners, for example, or strip utm params etc. - your users would certainly want people to click on their original URL.
