### ISSUE TITLE
Additional parameters not owki

### ISSUE THREAD

**Issue by luizbossoi** [itteco/iframely#190]
Hello guys

I'm trying to use parameters like 'iframe=amp' , 'lazy=1' but I get always the same response from API without these parameters

How can I enable it?

Thanks!!!

**Comment by iparamonau** [comment]
AMP and all other iFrame-related features are a part of the cloud. Renders are not included into self-hosted version as they require constant upkeep. 

The open source parsers return media from publishers as-is, perhaps the only exception being optional iFrame for the embeds that are not JavaScript-friendly, say Facebook posts.
