### ISSUE TITLE
Hitting twitter api limits - how to handle?

### ISSUE THREAD

**Issue by tombburnell** [itteco/iframely#191]
We are hitting twitter api limits. What options are there to handle this?
Does iframely support having multiple accounts?

**Comment by iparamonau** [comment]
That's perhaps the same as 192 and should now be fixed in v 1.2.5 available on NPM. Please re-open with further details if the issue persists.

**Comment by Serkan-devel** [comment]
@iparamonau OP can't re-open if you have closed it
