### ISSUE TITLE
Specific Twitter-Links in oEmbed will return link type object

### ISSUE THREAD

**Issue by mthomas87** [itteco/iframely#192]
I'm having a Twitter-Link which should return `"type": "rich"`
but returns `"type":"link"` when running the latest version locally (or deployed on our server).

The link is: https://twitter.com/janboehm/status/850101512546209792 (it contains a gif)
or another example is: https://twitter.com/EricTrump/status/997881301725302785 (is a retweet)

Running on localhost:
`http://localhost:8061/oembed?url=https://twitter.com/janboehm/status/850101512546209792`
or
`http://localhost:8061/oembed?url=https://twitter.com/EricTrump/status/997881301725302785`

returns "type":"link".

Compared to a tweet without specials: 

http://localhost:8061/oembed?url=https://twitter.com/realDonaldTrump/status/998256454590193665

returns "type":"rich"

what is what we always expect.

I can't comprehend what changed, because it worked last week.

Running all the links on your webapp https://iframely.com under "Check URL" and select "As oEmbed API" returns "type":"rich" as expected.

**Comment by iparamonau** [comment]
This should now be resolved in v 1.2.5 that has just been pushed to NPM. Twitter changed a few things on their end on Monday.
