### ISSUE TITLE
protocol relative URLs

### ISSUE THREAD

**Issue by cup** [itteco/iframely#195]
Iframely supports protocol relative URLs, such as:

~~~
//example.com/image.jpg
~~~

http://iframely.com/debug

However Facebook does not:

http://developers.facebook.com/tools/debug

Perhaps Iframely should be enforcing protocol absolute URLs?

**Comment by iparamonau** [comment]
Relative URLs are valid as far as Iframely core is concerned. We validate images, iFrames etc - and rejecting '//:' is impractical. For consistency, the API interface is also fine with such inputs. Changing that would mean bringing backwards incompatibility. So at this point, it's easier to handle such validation on the consumer end if need be.
