### ISSUE TITLE
Server error on specific type of Facebook-URLs

### ISSUE THREAD

**Issue by mthomas87** [itteco/iframely#196]
When entering some specific type of (still valid) Facebook-URLs, /oEmbed API endpoint returns 

`{"error":{"source":"iframely","code":500,"message":"Server error"}}`

Example URLs are:

https://www.facebook.com/PolizeiSuedhessen/posts/2220373718249525?__xts__[0]=68.ARBw3zkiqA-rdKNEod3pMH8oWocZtDJep9CIOIia2vOI_zKgEVylxnf1-Pp6zhJy4HGPGt8e3fiLj3QbLTB0x-xLVTjDGP0f-zsGC_WqcL_CtLhc_8joEcbjxCfEj3Xhn9HrZd1TQZo42vA1qg6jkMHpHZyM1pTMfSAPhOYYAztfC5v3-HcHnw&__tn__=-R

or

https://www.facebook.com/Bundespraesident.Steinmeier/posts/700030827034644?__xts__[0]=68.ARA42HdM-JIKGZ2vPnRswvrsxOutForkmS3yLs2Mced4C288-hzsaztxouQWmi96EQlEZ7QDdFjiDhr-rab1nQq2rBglMUmmfZb6OkKwgPir2WLePwHhqW973IpXIu8c5MPSR-5Enw1jw8uxhmGKY9cmltOKZ78Pbf-AwT0SIQ5i1ISGb8Nc&__tn__=-R

I don't know exactly where these URLs come from but 500 is definitely not expected.
What is the problem with these URLs? 

Tested with Version v1.2.6

**Comment by iparamonau** [comment]
Just tested it with the localhost and the issue won't repeat right away... 
Can you perhaps copy-paste some of the console logs for those URLs so that we can make a guess what might go wrong? Also, Node version would be great.

**Comment by mthomas87** [comment]
node version: v8.9.4

![bildschirmfoto 2018-09-03 um 16 52 26](https://user-images.githubusercontent.com/6641079/44993187-fb8d5200-af99-11e8-8e6a-0f5ab6e1a510.png)

**Comment by iparamonau** [comment]
Sorry, I meant the server console logs. 
Some stack trace after the message like

`-- [18-09-03 14:56:23] ::1 - Loading /oembed for https://www.facebook.com/...`

**Comment by mthomas87** [comment]
Ah sorry, only output is: 

```
-- [18-09-03 15:00:17] Whitelist activated. Domains, including blacklisted: 1979
'url' get param expected
```
when loading url in browser

**Comment by iparamonau** [comment]
`url` is in your API call as seen in the browser console. So that error was probably from some other request. 

But also, it appears that you don't URL-encode the URL (the last query-string param of the URL is treated as param for the API call itself). It shouldn't be a problem though, but could perhaps be in some web browsers.

In any case, in order to help, we'd need a bit more certain way to repeat the problem. Let us know if you can figure the steps/config/etc required.

**Comment by iparamonau** [comment]
Closing the issue for now - the test URLs work well both in the latest version of self-hosted Iframely, and in the cloud. Please reopen with the details if need be.
