### ISSUE TITLE
Processing error: HPE_INVALID_METHOD

### ISSUE THREAD

**Issue by NormandoHall** [itteco/iframely#197]
Hello

I have iFramely running in localhost and nodebb-plugin.iframely also. After upgrade nodejs to 10.x I get these error messages on all links in nodebb forum.

This is one example, and there is no render for the link, only as legacy <a href.

`[plugin/iframely] iframely responded with error: {"error":{"source":"iframely","code":417,"message":"Processing error: HPE_INVALID_METHOD"}}. Url: http://www.tortasycocteles.com/shop/index.php?id_category=50&amp;controller=category. Api call: https://iframely.vapeandoargentina.com.ar/iframely?url=http%3A%2F%2Fwww.tortasycocteles.com%2Fshop%2Findex.php%3Fid_category%3D50%26amp%3Bcontroller%3Dcategory&group=true`

Can I do something to fix this issue? Before nodejs upgrade runs ok.

NodeJS v10.4.1
NodeBB: v1.10.1
nodebb-plugin-iframely: 0.7.8
iframely: 1.2.5

Regards,
Normando Hall

**Comment by iparamonau** [comment]
That error occurs inside Iframely indeed, at the HTTP level. Node docs state that either HTTP GET request contains body, or there's error in HTTP headers from response. 

We checked with Node v10.4.1 and it all looks rosy in all our various environments. So it appears there's some HTTP middleware in your environment that might be causing the issue. Let's try and find it.

1. Please check Iframely server's console log and see if there are any stack traces there. You might also try changing `DEBUG: true` in your local config file - that should output more data to the console.

2. Try curling any failed URL from your server.
`curl -s -I -X GET "http://www.tortasycocteles.com/shop/index.php?id_category=50&amp;controller=category"`

3. Do you run Iframely through Docker by any chance? Also, what is your hosting service? Any proxies in use?

**Comment by iparamonau** [comment]
Thanks, that was helpful. The problem was between one of the libs we used and the node cluster. 
Please pull v1.2.7 from NPM, the issue should be resolved.

**Comment by NormandoHall** [comment]
Thank you so much @iparamonau ! Runs perfect!!!

**Comment by iparamonau** [comment]
OK, great. Thanks for submitting!
