### ISSUE TITLE
CACHE_ENGINE: 'redis' TTL issue

### ISSUE THREAD

**Issue by NormandoHall** [itteco/iframely#198]
Hello.

Switching to **redis** cache, and leave CACHE_TTL to 0 for "never expire" not work as when using node-cache o memcached. For redis expires inmediatelly. So, increasing CACHE_TTL comes to work as cache.

Same url: xxx

**CACHE_TTL: 0**

```
Loading /iframely for ...
Loading /iframely for ...
Loading /iframely for ...
Loading /iframely for ...
```

**CACHE_TTL: 1000000**

```
Loading /iframely for ...
Using cache for /iframely ...
Using cache for /iframely ...
Using cache for /iframely ...
```

**Comment by iparamonau** [comment]
Thank you, clarified the description in the example config.
