### ISSUE TITLE
less query parameter not working

### ISSUE THREAD

**Issue by ajayashuba** [itteco/iframely#200]
hi , i am using self-hosted version and the iframely=less is not having any effect . Does that query parameter have no effect on self hosted version ? 
and by default in self hosted version it is showing more whereas in iframely site by default it is less
for instagram embed the default setting is  params: {
                hidecaption: true
            } but actually it gives with extra column containing comment which is when hidecaption=false

**Comment by iparamonau** [comment]
right, more/less toggle for individual URL requests is the feature of the cloud. 

You may, however, configure 'more' or 'less' system-wide (=for all supported URLs) in your local config:

        providerOptions: {
            iframely: {
               more: true,
                //less: true
            }

**Comment by iparamonau** [comment]
For Instagram, there's an example of `ADD_OEMBED_PARAMS` to `hidecaption: true` in the example config.
