### ISSUE TITLE
Returns broken canonical URL

### ISSUE THREAD

**Issue by David-Shapira** [itteco/iframely#202]
Noticed broken canonical link when trying this URL
https://store.princeestate.com/store
iframely API returns the canonical link like this
https://store.princeestate.com/store.princeestate.com/store

Response:
`"meta": {
        "description": "Welcome to the Prince Official Store! Shop online for Prince merchandise, t-shirts, clothing, apparel, posters and accessories.",
        "title": "Prince | Official Store",
        "keywords": "Prince merchandise",
        "canonical": "https://store.princeestate.com/store.princeestate.com/store",
        "site": "Prince | Official Store"
    },
...`

Same on the iframely.com debug page: http://iframely.com/debug?uri=https%3A%2F%2Fstore.princeestate.com%2Fstore

**Comment by iparamonau** [comment]
Thank you! will be included into next version
