### ISSUE TITLE
Summary card

### ISSUE THREAD

**Issue by nums** [itteco/iframely#203]
On iframely.com, I've got an html data in the response with a beautiful summary card.
Is it possible to have the same result in open source version ?
I try with many params but It doesn't work for me.

Thanks

**Comment by iparamonau** [comment]
Some cloud features are not included into the open-source version. Mostly, all UI- and render-related ones, and that includes cards, sorry.
https://github.com/itteco/iframely#not-included-as-compared-to-cloud-api
