### ISSUE TITLE
Compact twitter embed url param not working?

### ISSUE THREAD

**Issue by leonkunert** [itteco/iframely#205]
We have been trying for some time to get the local version of iframely to render compact versions of twitter embeds. 
We are unsure as to weather we are doing something wrong or iframely is.
The url we are trying to send to iframely is ```https://twitter.com/gee4mac/status/1055607929192108037?iframely=less``` 
The debug interface reports calling this url: ```http://localhost:8061/iframely?uri=https%3A%2F%2Ftwitter.com%2Fgee4mac%2Fstatus%2F1055607929192108037%3Fiframely%3Dless```

Can you help us with what we are doing wrong, or why it isn't working.

Best regards

**Comment by iparamonau** [comment]
Our more/less toggle only works in the cloud, sorry. 
(But your Twitter URL is at its minimal form already as we hide the conversation by default in the cloud). 

You can configure Twitter for your local instance with any params that Twitter supports. 
See `twitter` section in config's `providerOptions`
https://github.com/itteco/iframely/blob/master/config.local.js.SAMPLE#L155

In your case, I suppose, you're looking to change `hide_thread` to `true`

**Comment by leonkunert** [comment]
Could you be so nice and write this crucial information into your docs on the website. It took us way too long to get this information and could leet to some more purchases of the cloud service.
