### ISSUE TITLE
Missing html object in liveleak response

### ISSUE THREAD

**Issue by angorzan** [itteco/iframely#208]
Liveleak has changed their link pattern, after view? there is now letter t instead of i. What is more, after those changes I didn't get html object inside response.
Is it possible to fix it?

**Comment by iparamonau** [comment]
Liveleak parser stopped working in May 2018 and was removed in v1.2.5. Provider was assessed as unstable and is no longer supported in self-hosted version. Just to remind: you can expand Iframely with your own plugins (via `CUSTOM_PLUGINS_PATH` in your config)
