### ISSUE TITLE
img width and height

### ISSUE THREAD

**Issue by ajayashuba** [itteco/iframely#209]
how to i set img width and height to 100% to url like ```https://i.redd.it/r9hi7rpq97b21.jpg```

**Comment by ajayashuba** [comment]
if i give url like above it create a img tag but this image overflows the parent container so by default you should have had it set it style width,height to 100%

**Comment by iparamonau** [comment]
Ok, got it. You can actually do it via CSS on your page.

Here's for example how Bootstrap defines it:

```
img {
    max-width: 100%;
    width: auto;
    height: auto;
    vertical-align: middle;
    border: 0;
    -ms-interpolation-mode: bicubic;
}
```
