### ISSUE TITLE
Strange cache behaviour

### ISSUE THREAD

**Issue by hotrush** [itteco/iframely#210]
![peek 2019-01-22 17-40](https://user-images.githubusercontent.com/1247004/51542710-f0fe2700-1e6c-11e9-8581-243c62764c5f.gif)

I am using self-hosted version. Just reloading page at browser for the same url and randomly getting different results - it can be normal result, but can be 408 timeout error. But logs saying that cache is used. Don't sure how this possible.

**Comment by iparamonau** [comment]
It looks different processes in your cluster have different cache. One has timed-out result. 

What caching engine is in use? The default one is node-cache in-memory cache, which would explain why cache isn't shared between the processes.

**Comment by hotrush** [comment]
@iparamonau thanks, will try
