### ISSUE TITLE
cordova issue

### ISSUE THREAD

**Issue by ajayashuba** [itteco/iframely#211]
how do i use it in mobile platform since in cordova everypage loads using file protocol using embed like ```<blockquote class="imgur-embed-pub" lang="en" data-id="a/nRn4f5s"><a href="https://imgur.com/a/nRn4f5s">The City made a 'new' road first time in 5+ years in front of my home</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>```

will use ` //s.imgur.com/min/embed.js` as `file//s.imgur.com/min/embed.js`

**Comment by ajayashuba** [comment]
another solution is i can use regex but too many domains have the same format is there any purpose of not  specifying any protocol to use for download ?

**Comment by ajayashuba** [comment]
[https://imgur.com/a/TC8ItUy]('check this')

**Comment by iparamonau** [comment]
Regex'ing protocol-less srcs is the way to go for Cordova if you self-host. The src comes directly from Imgur, and the reason is that if you don't need https, http would be a) faster b) cheaper for Imgur's CDN use.

**Comment by ajayashuba** [comment]
if you are already figured out can you share the regex ?
