### ISSUE TITLE
Change invalid requests to 4xx errors

### ISSUE THREAD

**Issue by marwonline** [itteco/iframely#213]
Hi there,
currently when calling the endpoints without providing a proper URL I'm getting a 500 error. As the client did the mistake here I'd suggest to change this to a 400 error.

Version: v1.0.2
Environment: self-hosted

Calling: `GET /oembed?url=`
will lead to
```
{
  "error": {
    "source": "iframely",
    "code": 500,
    "message": "Server error"
  }
}
```
but IMHO should be:
```
{
  "error": {
    "source": "iframely",
    "code": 400,
    "message": "Bad Request: 'url' get param expected"
  }
}
```

Affected endpoints:

- /iframely https://github.com/itteco/iframely/blob/master/modules/api/views.js#L94
- /render  https://github.com/itteco/iframely/blob/master/modules/api/views.js#L284
- /oembed https://github.com/itteco/iframely/blob/master/modules/api/views.js#L398

Does this sound like a valid feature request? Do you need help with the implementation? Something else?

**Comment by iparamonau** [comment]
Thank you. We'll add the extra validation for the empty URL inputs in the next version.
