### ISSUE TITLE
Iframely as Node.js library 

### ISSUE THREAD

**Issue by a-reda** [itteco/iframely#216]
> Iframely can also be used as Node.js library (that's how it is used in our cloud API).

Citing the documentation, it is possible to use Iframely as a library. 

Any example/guide on how to achieve this easily and without including useless libraries (such as aws-sdk) ?

**Comment by iparamonau** [comment]
Such issue is already open for a while - #186. We know we owe you guys proper docs with that regard. In the meantime, @dhamaniasad has a good write-up mentioned in [this comment](https://github.com/itteco/iframely/issues/186#issuecomment-458912281)
