### ISSUE TITLE
Giphy links return 403 forbidden

### ISSUE THREAD

**Issue by David-337** [itteco/iframely#227]
Hi, hope you are doing well.
In the last couple of days I noticed that any Giphy link that I send to the hosted version returns a 403 forbidden error.

Example: .../iframely?url=https://giphy.com/gifs/half-life-dgUkGIl6gfn2w
Returns `{
    "error": {
        "source": "iframely",
        "code": 403,
        "message": "Forbidden"
    }
}`

Giphy appears to be working fine in the cloud version, perhaps this is a config issue?
I am able to reproduce this problem with the default config.local.js on both master and develop branches.

**Comment by tony5Dim** [comment]
Same here 403 forbidden.
Anyone to help please ?

**Comment by iparamonau** [comment]
Sorry, folks. Nothing we can help you with. 

Giphy turned on bot protection, and it's not specific to Iframely. Here's same issue with cUrl:

`$ curl -I https://giphy.com/gifs/half-life-dgUkGIl6gfn2w
HTTP/2 403 `

I can hint that you may try and overcome that with some changes in your Iframely config. See sample file for inspiration. But we can't share our own cloud config. It is outside of the support scope for this project, sorry.
