### ISSUE TITLE
Custom providers ?

### ISSUE THREAD

**Issue by mahmoudps** [itteco/iframely#231]
Hi ,
how can i add my own provider with self hosted iframely ?
i try to modify the file oembed/providers.json & add it ,,
but it's not work ..

**Comment by iparamonau** [comment]
As the sample config file [suggests](https://github.com/itteco/iframely/blob/master/config.local.js.SAMPLE#L4-L5), you can have a directory (anywhere) with all your custom plugins:

```
        // Specify a path for custom plugins. Custom plugins will override core plugins.
        // CUSTOM_PLUGINS_PATH: __dirname + '/yourcustom-plugin-folder',
```

So basically, take a look at the other plugins Iframely comes with and you can implement/change your own in a similar way (sorry, no detailed plugins doc). To override any of the existing plugins - simply create the plugin with the same file name in your private dir.

**Comment by luminous8** [comment]
Doc on plugin would be awesome. Hard to understand how it works without any documentation

**Comment by iparamonau** [comment]
@luminous8 there's an unfinished doc about the plugins in the /docs dir:
https://github.com/itteco/iframely/blob/master/docs/WRITE-A-PLUGIN.md. Not sure if it makes it easier though.  Take a look into other plugins to get a better idea.

**Comment by uschwarz** [comment]
Note: don't use `..` in the `CUSTOM_PLUGINS_PATH`, because the overriding check looks at it verbatim and won't realize that `/path/to/my-extra-plugins/thing.js` is in the custom directory `/path/to/iframely/../my-extra-plugins/thing.js`.

(Maybe should config.local.js.sample recommend

    // CUSTOM_PLUGINS_PATH: resolve(__dirname + '/yourcustom-plugins-folder/'),

to be on the safe side?)

**Comment by iparamonau** [comment]
@uschwarz At the moment the sample config file suggests 

`CUSTOM_PLUGINS_PATH: __dirname + '/yourcustom-plugin-folder'`

Seems to work fine for us.
