### ISSUE TITLE
Getting 429 responses from youtube.

### ISSUE THREAD

**Issue by tombburnell** [itteco/iframely#234]
We've started getting 429 responses from youtube. Looks like we've reached the rate limiter.
Whats the best approach - Can we pay for  an api-key to get a higher rate? how does one obtain it?

**Comment by iparamonau** [comment]
As I see it in the plugin code, Iframely should fallback to the generic parsers and this means you should still get a video from twitter player, og video or oembed. 

So, youtube's 429s are handled and covered that way already. 

Besides trying to increase your rate limits with YouTube, you may also try configuring longer cache TTL for Iframely via `API_REQUEST_CACHE_TTL`. This TTL targets API requests to publishers -  i.e. covered google data requests that results in 429 for you.

**Comment by tombburnell** [comment]
`As I see it in the plugin code, Iframely should fallback to the generic parsers and this means you should still get a video from twitter player, og video or oembed.`
I'm not sure I follow. Are you saying if it can't embed via youtube it would go to twitter? How could that work?

if I go to:
http://iframely-host:8080/iframely?url=https://www.youtube.com/watch?v=oWC6x4Qqwe4

I'm getting 
{"error":{"source":"iframely","code":429,"message":"Server error"}}

I see this in the config. which key type is this?
```
            // List of query parameters to add to YouTube and Vimeo frames
            // Start it with leading "?". Or omit alltogether for default values
            // API key is optional, youtube will work without it too.
            // It is probably the same API key you use for Google Maps.
            youtube: {
                // api_key: "INSERT YOUR VALUE",
                get_params: "?rel=0&showinfo=1"     // https://developers.google.com/youtube/player_parameters
            },
```
We have a google youtube api key of the form:  10xxxxxxxxx-egisehfse3o9j8gexxx.apps.googleusercontent.com/

I've tried adding this but it hasn't helped. I'm not sure if it is the right key? Do you know which key is needed?

The fact that it says "probably the same as maps.google.." sounds like it's not really known.

**Comment by tombburnell** [comment]
oh - I found this method to generate the right kind of key.. now it works again!
https://kodicommunity.com/how-to-fix-youtube-quota-limit-exceeded-on-kodi/

**Comment by iparamonau** [comment]
Ok, thanks for the reference.

What I meant is that you may skip youtube API key completely in your config, and Iframely will still work via the default oEmbed/Twitter player parsers for YouTube.

Also, the same fallback should happen if YouTube data API returned 429 - the URL processing should fallback to oEmbed, not return an error in the end. Let us know if it doesn't.

**Comment by tombburnell** [comment]
That doesn't seem to be the case. As I mention above, we get
{"error":{"source":"iframely","code":429,"message":"Server error"}}

We have now added a key but it seems we have now bust the 150k quota for youtube LIST operations. We don't understand whats going on. 

It was working but now and then having some difficulties, so we upgraded to the latest version.

Then we started getting a lot of 429 failures and it appeared we hit the 10k default limit without using a KEY. Now we've given it a KEY and we're almost immediately hitting 150k/day limit.

And you're saying it should work without the key anyway. 

Is there something we need to do to configure the oEmbed/Twitter in the config.

Here is our config - can you advise if we are missing something?

```
(function () {
    var config = {
        DEBUG: process.env.DEBUG,
        DISABLE_HTTP2: true,
        CLUSTER_WORKER_RESTART_ON_PERIOD: 5 * 3600 * 1000,      // 5 hours.
        CLUSTER_WORKER_RESTART_ON_MEMORY_USED: 150 * 1024 * 1024,     // 150 MB.
        RICH_LOG_ENABLED: false,
        baseAppUrl: process.env.BASE_APP_URL || "http://xxx.xxx.xx",
        relativeStaticUrl: "/r",
        port: process.env.MYPORT || 8080,

        /*
         Supported cache engines:
         - no-cache - no caching will be used.
         - node-cache - good for debug, node memory will be used (https://github.com/tcs-de/nodecache).
         - redis - https://github.com/mranney/node_redis.
         - memcached - https://github.com/3rd-Eden/node-memcached
         */
        CACHE_ENGINE: process.env.CACHE_ENGINE || "no-cache",
        CACHE_TTL: process.env.CACHE_TTL_SECS || 24 * 60 * 60, // In seconds.
      metaLoadingTimeout: 5 * 1000,
        providerOptions: {
            "twitter.status": {
                "min-width": 250,
                "consumer_key": process.env.CONSUMER_KEY,
                "consumer_secret": process.env.CONSUMER_SECRET,
                "access_token": process.env.ACCESS_TOKEN,
                "access_token_secret": process.env.ACCESS_TOKEN_SECRET,
                "hide_media": false,
                "hide_thread": false,
                "omit_script": false
            },
            "facebook": {
                "width": "auto"
            },
            "flickr": {
                //"apiKey": 'INSERT YOUR VALUE',
            },
            "google.maps": {},
            "readability": {
                "enabled": true
            },
            "images": {
                "loadSize": false, //# if true, will try an load first bytes of all images to get/confirm the sizes
                "checkFavicon": false //# if true, will verify all favicons
            }
             },
//# List of query parameters to add to YouTube and Vimeo frames
//# Start it with leading "?". Or omit alltogether for default values
            "youtube": {
                "api_key": "xxxxxxxxxxxxxxxxxx",
                "get_params": "?rel=0&showinfo=1"  //   # https=>//developers.google.com/youtube/player_parameters
            },
            "vimeo": {
                "get_params": "?byline=0&badge=0"   //  # http=>//developer.vimeo.com/player/embedding
            }
        },
        OEMBED_RELS_PRIORITY: ["app", "player", "survey", "image", "reader"]
    };
    module.exports = config;
    console.log("LOCAL CONFIG", config);
})();
```
~

**Comment by iparamonau** [comment]
So it looks you get 429 error twice - first time on the domain plugin with your API key. Then the plugin falls back to generic parsers - which means making HTTP call to YouTube again.  And this is where you get your final 429 from... Looking into the code, that's the only possible way you could receive a 429. 

Now, to your config. 
```
CACHE_ENGINE: process.env.CACHE_ENGINE || "no-cache",
CACHE_TTL: process.env.CACHE_TTL_SECS || 24 * 60 * 60, // In seconds.
```
What do you pass there as the env variables? It appears that you simply have no cache in place - hence overloading YouTube. Also, if you use Memcached or Redis, there should be a separate config options for them too in the file.

Once you sort out how your cache is set up, I'd suggest again to add `API_REQUEST_CACHE_TTL` (in secs) and set it to 30 days. That will be the ttl for YouTube requests and will definitely solve your problems.

**Comment by tombburnell** [comment]
But we were getting those 429 error responses before adding a key.

I don't follow your reasoning. You say after failing _with_ a key, it then uses a generic parser which calls youtube again and that can result in a 429. So does it not follow that if you have no key, it uses the generic parser, calls youtube and may also return a 429?

Those cache settings are not currently defined, however we do have a varnish cache in front of our iframely servers. Would an iframely internal cache add anything beyond what the varnish cache does?

**Comment by tombburnell** [comment]
This is what was shown in the log at the time

 -- [20-02-13 14:46:25]:14219    -- plugin redirect (by "htmlparser") https://www.youtube.com/?feature=youtu.be
 -- [20-02-13 14:46:25]:14219    -- plugin response: {"plugin":"htmlparser","response":429,"uri":"https://www.youtube.com/watch?v=k_VGzhW8lpM&feature=youtu.be&t=304"}

There was no key present at the time.

**Comment by iparamonau** [comment]
Yes, that is exactly what I meant. You get 429 HTTP error when our parsers try to fetch youtube/watch page. But when you enter API key, we don't even fetch their pages - we go straight to their Data API. And _only_ if we get an error there (including 429), we then go the regular route of fetching the http page and trying to get players in other standard ways. Hence I call it a "fallback". But it looks you get 429 on the fallback as well. And so you need to figure out your caching. 

It's either your varnish doesn't keep the cache long enough, or it has many edge locations all of them going to Iframely instance - and missing the cache, and hitting YouTube again. As I said, I can imagine you could easily create quite a load to them that way. 

Keeping Iframely cache in Iframely instance makes sure you don't call YouTube again for a long while. 

Last, but not least - if you have multiple instances of Iframely, then we suggest to share the cache between them (say, distributed memcached) - as otherwise each instance will create its own load to YouTube under the same API key with them.

**Comment by tombburnell** [comment]
Right thanks - starting to make a bit more sense now. I guess there are 2 limits - the api quota and a public rate limit and we're hitting both. 

We've made a request for a higher api limit and will try to fine tune our caching and maybe look at the iframely internal cache. 

Thanks for patiently explaining.

**Comment by tombburnell** [comment]
Hi - out of interest, how many requests does iframely to youtube per call to iframely? just 1 or more?
Because we are noticing a much larger use of our google-api quota than the number of requests to iframely we make for youtube embeds.

**Comment by iparamonau** [comment]
It should be one call per URL. However, they count some sort of credits, not the API requests. And the credits depend on the information you request. We don't request all infos, but about 3 of their sections they they count.

**Comment by sielay** [comment]
We noticed we don't need all fields that are currently requested from Google API. I will prepare PR that will allow configuring of what is being requested.

**Comment by iparamonau** [comment]
Thanks, sounds good. But it can't be the root cause. I still believe that your answer is a proper caching. 

These vars should be set up in config for the overall cache TTL:

```
CACHE_ENGINE: process.env.CACHE_ENGINE || "no-cache",
CACHE_TTL: process.env.CACHE_TTL_SECS || 24 * 60 * 60, // In seconds.
```

You can also tune cache TTL for all data requests (like YouTube API) via `API_REQUEST_CACHE_TTL`, or even tune ttl specifically for YouTube Gdata via `cache_ttl` property of `PROXY` entry (leave the rest properties of a record empty for default values).

**Comment by sielay** [comment]
@iparamonau I'm not saying you're wrong (I think you're right), but the cache is something we can tune along. Size of fetched data has a direct effect on quota being used and in our case (really massive number of requests) small margin scales to massive numbers.

So approach we'd take here would be:

 1. avoid fetching data we don't need
 2. tune cache

Also, as @tombburnell mentioned we have Varnish in front so service is not even hit for most of the calls. If we wouldn't have it then your suggestion with it would be point number 1.

**Comment by iparamonau** [comment]
I've just checked what cache-control headers our self-hosted version exposes. And it actually appears to be none (`etag` doesn't help as in case you don't have internal cache. It actually takes the full run, including a request to YouTube, to recalculate the etag. `date` is also a new timestamp every time).

So I hope your Varnish doesn't rely on our upstream for cache orchestration and overrides/hardcodes the ttl with its default value. It should be quite substantial if you have massive amount of YouTube videos. I'd say at least 24 hrs.

**Comment by sielay** [comment]
We have a pretty bit TTLs and base cache on full URL. But will ask team to verify. Thanks

**Comment by sielay** [comment]
Also, some code still uses `jsonp`, because of which (as callbacks are generated automatically) `etag` caching won't help much. But your internal cache seems to handle that pretty well.

**Comment by tombburnell** [comment]
At the moment, due to our quota problems, we cache every unique 200 response for at least 30 days and our cache hit rate is about 87% for youtube requests. We are also caching 429s for a few hours and 404s for a considerable period. 

Ideally we would have a faster response to data change and video deletions and I presume the etag could help us with that but we can handle that in other ways. 

This PR Lukasz has made should reduce our quota by about 75% so it should make a massive impact for us.

**Comment by iparamonau** [comment]
I'd assume this one is resolved now.
