### ISSUE TITLE
Override generic fallback 

### ISSUE THREAD

**Issue by bahaeddine4** [itteco/iframely#235]
Hello , 
 is it possible to `override falling back from domain to generic` by a custom plugin ?

**Comment by iparamonau** [comment]
Yes, sure. Your custom plugin should match the URL from a domain in this case, return some value in the method getLink (even if it's just a favicon). 

Also, non of the domain plugins (original one or fallback), should use `"*"` mixin - this adds all the default generic parsers.

**Comment by bahaeddine4** [comment]
@iparamonau Thank you for you answer , but I don't think I made myself clear , what I want is not just a fallback for a specific domain , but a way  (custom plugin or something else) to handle all the non supported domains by Iframely, Is it possible ?

**Comment by iparamonau** [comment]
There are domains that are covered by generic providers through the central whitelist. Like, for example, most oEmbed. 

So essentially, you won't know whether a domain is supported until after the entire Iframely cycle is finished. You could perhaps try to do something with [validator plugins](https://github.com/itteco/iframely/tree/master/lib/plugins/validators), but I trust it is easier to add a fallback just outside of Iframely. When you receive an answer - check and do the required fallback. You can add generic providers that will add the data you need for an external fallback.

**Comment by bahaeddine4** [comment]
alright , thank you @iparamonau
