### ISSUE TITLE
Reverse Proxy & EmbedJS help

### ISSUE THREAD

**Issue by pecagg** [itteco/iframely#257]
I've managed to create a proxy for /iframely, but I feel like I'm stuck.
`/iframely           -- main API endpoint with get params `

I do get the good JSON results when I access `myhost/iframely/?url=xxxxx`

This is my current nginx configuration:
```
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
		index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		
	location /iframely {
        proxy_pass http://localhost:8061;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
...

    }
```

The question is, how can I connect the **embed.js** with the iframely? 
Is it supposed to be in the same dir as the iframely, and then executed from the webpage?

I've tried hosting it on the same VPS as iframely - but I can't get it how to set the reverse proxy to work..

I've tried putting it in the nginx config like this, but i couldn't make it work (can't access embed.js trough browser):
```
...
	location / {
		
		location /js {
		root /embedjs/dist/;
		}

		 location /iframely {
        proxy_pass http://localhost:8061;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
 ...

```

My embed.js file is located in **~/root/embedjs/dist/**
Iframely is located in **~/root/iframely**

I'm trying to get `<oembed url="xxxxx"></oembed>` formated correctly using iframely and embed.js

I'm a beginner, so sorry if my questions don't make sense.
Thank you!

**Comment by iparamonau** [comment]
Hey, sorry we missed that at the time. 

As it is mentioned quite explicitly in Embed.js readme, the script can only work with the cloud, based on our hosted iFrames. It has never worked with the self-hosted version, sorry.
