### ISSUE TITLE
GoogleMaps: need better view to span and zoom convertion

### ISSUE THREAD

**Issue by nleush** [itteco/iframely#27]
Someone who knows about longitude/latitude calculations could convert the long+lat+view diameter (I think in meters) of the new Google maps into long+lat+span in degrees of the embed code and long+lat+zoom for the given resolution of the thumbnail. I don't feel like learning this kind of math so I just did a quick conversion of the diameter to a zoom value (the embeds accept long+lat+spn or long+lat+zoom). However, the zoom value is probably only correct under a certain window/iframe size (it is correct for me for maximized browser windows; my screen resolution is 1920x1080). So the embed shows the correct coordinates, but they only show the correct area if the original URL already had a spn query parameter. The way I did it the thumbnail will probably never show the exactly correct area, because it needs a zoom value (doesn't accept spn). I would need to convert the spn to a zoom for the given width/height. If the original URL has no zoom (only a spn) the thumb currently has zoom=0 (completely zoomed out). You get such URLs if you go to a new Google Maps URL but you don't have opted in to the new Google Maps GUI.

So if someone who knows this sort of maths would take a look at it, the generated embed code and thumbnails could be much better (show precisely what the user viewed in Google Maps before).

**Comment by iparamonau** [comment]
Done in the new google maps plugin
