### ISSUE TITLE
Datawrapper embeds not responsive

### ISSUE THREAD

**Issue by zeitwidrig** [itteco/iframely#272]
[Datawrapper](https://www.datawrapper.de) provides 2 embed methods: a static Iframe and a responsive Iframe.
For the responsive iframe they include a script which adds a postMessage EventListener which resizes the Iframe if necessary.

The Datawrapper API returns both the Iframe and the script: https://api.datawrapper.de/v3/oembed?format=json&url=https%3A%2F%2Fdatawrapper.dwcdn.net%2Fjz8IZ%2F1%2F

iFramely omits the script which leads to a [static non-responsive iframe](https://iframely.com/embed/https%3A%2F%2Fdatawrapper.dwcdn.net%2Fjz8IZ%2F). 
This is problematic for infographics which are designed in a vertical format, e.g. https://datawrapper.dwcdn.net/jz8IZ/

Any chance iFramely could provide the responsive Iframe by default?

**Comment by iparamonau** [comment]
Thanks. We've reviewed the whitelist record for datawrapper and changed it to include script. Restart your Iframely server if it doesn't show up for you.
