### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by freestylemaster** [itteco/iframely#275]
Hi,

I am getting 'timeout' error on all urls. I was wondering if you have any idea what could be the issue?

Web;
`{"error":{"source":"iframely","code":408,"message":"Timeout"}}`

Logs;
`1|iframely  | -- [20-07-17 03:58:21]:1215    -- plugin response: {"plugin":"htmlparser","response":"timeout","uri":"xxxx"}`
`1|iframely  | Processing error: timeout`
`0|iframely  | -- [20-07-17 03:58:21]:1208    -- plugin response: {"plugin":"htmlparser","response":"timeout","uri":"xxxx"}`
`0|iframely  | Processing error: timeout`

**Comment by iparamonau** [comment]
If it happens on every URL, the problem can be  with your local internet connection.

Timeout happens when we initiate HTTP request and receive no answer for about 30 seconds, but that's configurable. Try increasing it and see if it helps.

**Comment by kookster** [comment]
This is happening to me too, on every request, from a dockerized instance, using default config for timeout values.
It also happens when deployed to AWS, so this is not a local internet connection issue.

**Comment by kookster** [comment]
did some more debugging: for me, seems to only be https requests

**Comment by freestylemaster** [comment]
I have no local internet issue as I can reach to same exact links where I get the error

**Comment by iparamonau** [comment]
It's started to sound like there's a HTTP/2 issue. Try disabling it and rolling back to HTTP 1.1

`DISABLE_HTTP2: true` in your local config.

**Comment by kookster** [comment]
Thanks @iparamonau, I will try the `DISABLE_HTTP2` suggestion and report back.

In the meantime I downgraded to node 10, and it works.

I also tried keeping node 12 and trying different versions of alpine. That did nothing, but everything works after dropping down to node 10.

**Comment by kookster** [comment]
that worked! moved back to node 12, and just `DISABLE_HTTP2: true` was sufficient to get things working again.
thanks @iparamonau !

**Comment by freestylemaster** [comment]
`DISABLE_HTTP2: true` also worked for me! Thank you
