### ISSUE TITLE
FR: Typescript Support

### ISSUE THREAD

**Issue by kwasimensah** [itteco/iframely#278]
Hi, I was exploring using iFramely for a project but was wondering if there are any plans for Typescript support. Thanks.

**Comment by iparamonau** [comment]
We recommend using Iframely as a separate running API instance. In that sense, Typescript as any other programming languages are already supported. You simply need to make API calls via HTTP and receive JSON data back for parsing.

**Comment by kwasimensah** [comment]
For context, I wanted to sit some of my authentication logic in front of the iframely instance to make sure my servers are the only ones that are using it. I'll look into some other way of locking down who can talk to the custom instance.

**Comment by kwasimensah** [comment]
I saw you have an allowed origins check but that header can be faked by a malicious actor.
