### ISSUE TITLE
Spotify playlists don't work

### ISSUE THREAD

**Issue by jangarcia** [itteco/iframely#279]
In 1.4.5, Spotify playlists like https://open.spotify.com/playlist/60DANKGkHJTt9fRr5RZLWr don't seem to work anymore, same on iframely.com.

**Comment by iparamonau** [comment]
Unfortunately, it looks like Spotify has started returning 404 error on the playlists:

```
- Loading /iframely for https://open.spotify.com/playlist/60DANKGkHJTt9fRr5RZLWr
-- plugin response: {"plugin":"htmlparser","response":404,"uri":"https://open.spotify.com/playlist/60DANKGkHJTt9fRr5RZLWr"}
```

```
$ curl -I https://open.spotify.com/playlist/0OV99Ep2d1DCENJRPuEtXV
HTTP/2 404 
```

It also appears that they have disabled their oEmbed endpoint recently. 

As the results, we won't be able to do anything about it. Not in the source code of open-source version anyway. We'll probably be removing the domains plugins for Spotify in the next version if things don't get fixed on their end, sorry.

**Comment by jangarcia** [comment]
@iparamonau The oembed-Endpoint works for me: 

```
curl -I https://open.spotify.com/oembed?url=https://open.spotify.com/playlist/60DANKGkHJTt9fRr5RZLWr
HTTP/2 200 
```

Spotify has acknowledged this as a bug, though, so maybe it's only working sporadically or under certain conditions, see [this comment](https://community.spotify.com/t5/Spotify-for-Developers/Playlist-oembed-down-or-changed/m-p/4963963/highlight/true#M290).

**Comment by iparamonau** [comment]
indeed, their oEmbed is now back to normal - thanks for heads-up. We were dealing with their oEmbed errors on Friday, hence the status.

I've added the fallback for 404 on playlists for now (see [commit](domains: add a fallback for 404s on Spotify playlists) in develop branch). If they resolve the issue, simple configure `spotify.ignore_errors` back to false to disable that fallback.
