### ISSUE TITLE
Facebook videos stopped parsing - 404

### ISSUE THREAD

**Issue by lynxlynxlynx** [itteco/iframely#282]
Hey,

here are two URL versions of the same video:
https://www.facebook.com/watch/?v=216496276334229
https://www.facebook.com/storyofstuff/videos/216496276334229/

at some point iframe.ly stopped parsing them. I only get a 404 from:
https://iframely.com/embed/https%3A%2F%2Fwww.facebook.com%2Fstoryofstuff%2Fvideos%2F216496276334229%2F

It used to work; wouldn't even have noticed a problem if a bug in gutenberg didn't make this exponentially worse.

Any ideas?

**Comment by iparamonau** [comment]
Facebook says that the video can no longer be embedded because of the copyright claim:
https://www.facebook.com/plugins/video.php?href=https://www.facebook.com/storyofstuff/videos/216496276334229/

So the best we could do is it create a summary card instead. We'll check if that is feasible.

**Comment by lynxlynxlynx** [comment]
Hmm, that's pretty opaque from FB. A placeholder with a clickable URL sounds like a good mitigation method though.

**Comment by iparamonau** [comment]
This should now be resolved in `develop` branch
