### ISSUE TITLE
Facebook and Instagram - breaking changes on Oct 24, 2020

### ISSUE THREAD

**Issue by iparamonau** [itteco/iframely#284]
Facebook and Instagram both are retiring their public access to their open oEmbed endpoints on October 24:
https://developers.facebook.com/docs/plugins/oembed-legacy

The [replacement endpoints](https://developers.facebook.com/docs/plugins/oembed) will require you to register for a [FB app](https://developers.facebook.com/docs/apps#register) and activate oEmbed product. It goes without saying that in the process you'd have to accept FB developer terms of use...

We're working on the fix ([done](https://github.com/itteco/iframely/commit/17398ad49d71c3137b119e460c5ebe9a222f377f)) and will publish it in v1.5.0. It's not complicated itself, but it will be introducing breaking changes and will require an additional configuration step before you update. We'll be adding the configuration instructions to the description of this issue ( below) when they are ready. 

Please feel free to add comments to this issue if you need support. We'll keep this issue open for a while until the migration is completed.

### Configuration instructions for new endpoints.

Please see changes in [config.local.js.SAMPLE](https://github.com/itteco/iframely/commit/fececd3b9a6570b5626c5d88c93405e5eec2456e) for what needs to be changed. 

The new Facebook and Instagram endpoints require `access_token=`  query-string parameter be added to the request. Iframely supports it by default via` ADD_OEMBED_PARAMS` configuration. Add a regex to new endpoints and specify your access token as a parameter to add. It is easiest if you use `{app-id}|{app secret}` as your token (with `|` as separator).  

You can get App ID and App Secret parts of the access token on Facebook developer dashboard -> Settings -> Basic.

```
ADD_OEMBED_PARAMS: [{
    re: [ // Endpoint's URL regexp array.
        /^https:\/\/graph\.facebook\.com\/v\d+\.\d+\/instagram_oembed/i,
        /^https:\/\/graph\.facebook\.com\/v\d+\.\d+\/oembed_/i
    ],
    params: { // Custom query-string params object.
        access_token: '{App ID}|{App Secret}',
    }
}]
```

If you already use other separate oEmbed parameters for Instagram or Facebook, you can create several regex records in `ADD_OEMBED_PARAMS` array.

**Alternatively**, you can pass your access token as HTTP header, using `PROXY` configuration:
```
PROXY: [{
    re: [
        /^https:\/\/graph\.facebook\.com\/v\d+\.\d+\/instagram_oembed/i,
        /^https:\/\/graph\.facebook\.com\/v\d+\.\d+\/oembed_/i    
    ],
    headers: {
        authorization: 'Bearer {ACCESS TOKEN HERE}'
    }
}],
```

The proxy method is more error-prone for configuring, but it allows you to conceal your access token to some extent. It also lets you keep your other oembed parameters configuration separate. And, finally, if you ever need to change the access token, the oembed cache won't be dropped because headers are not part of the cache key, unlike query-string parameters that are.

**Comment by iparamonau** [comment]
v 1.5.0 is now pushed to NPM. Please follow instructions in the body of this issue before updating.

**Comment by iparamonau** [comment]
With the exception of the retired `/media` endpoint of Instagram, everything works well in 1.5.0. Instagram /media endpoint [will be retired in 1.5.1](https://github.com/itteco/iframely/commit/bb98dbcdc1a1267c41ffbe04eb55117d6f5f742f).

**Comment by luminous8** [comment]
Regarding the retired /media enpoint, do you know how to get the fullsize image (similar to /media?size=l)?

**Comment by iparamonau** [comment]
We just get it [from og image](https://github.com/itteco/iframely/blob/bb98dbcdc1a1267c41ffbe04eb55117d6f5f742f/plugins/domains/instagram.com.js#L85-L98). The image looks to be good enough.

**Comment by luminous8** [comment]
It's seems that the og image is a low res whereas the /media endpoint allowed us to get an high res image. I guess that wanted from their side.

**Comment by iparamonau** [comment]
I trust L size was 1080x1080 and it's 1080x1080 now in og.image, no?

**Comment by luminous8** [comment]
Could it depend on the post?
For example with this post https://www.instagram.com/p/CGDu5POHxVO/?hl=fr I get a [480x480](https://scontent.cdninstagram.com/v/t51.2885-15/e35/s480x480/120914494_622612125025678_571712506262087388_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_cat=110&_nc_ohc=2W27CBaktfUAX-90rKN&_nc_tp=15&oh=407358b905726cc34bd7e6109fe2c458&oe=5FBF6EF4) but the [1080x180](https://scontent-cdt1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/120914494_622612125025678_571712506262087388_n.jpg?_nc_ht=scontent-cdt1-1.cdninstagram.com&_nc_cat=110&_nc_ohc=aim6stxqYyUAX_4mtCd&_nc_tp=15&oh=72970b15859f4f74d21dce49670a8a4e&oe=5FC31E4A) exists.

**Comment by iparamonau** [comment]
@luminous8 interesting. I get 1080x1080 for og image on your URL. Are you sure you're talking about OG image and the code version from `develop` branch (not yet in master/NPM)? Cause 480x480 is oEmbed thumbnail and it indeed exists in the v1.5.0 as well.

**Comment by luminous8** [comment]
I got this results from iframely directly.

A few examples where I don't get the high res image:
[https://iframely.com/embed/https%3A%2F%2Fwww.instagram.com%2Fp%2FCG3ELq6HA3D%2F](https://iframely.com/embed/https%3A%2F%2Fwww.instagram.com%2Fp%2FCG3ELq6HA3D%2F)
[https://iframely.com/embed/https%3A%2F%2Fwww.instagram.com%2Fp%2FCGyDVUUnpvn%2F](https://iframely.com/embed/https%3A%2F%2Fwww.instagram.com%2Fp%2FCGyDVUUnpvn%2F)
[https://iframely.com/embed/https%3A%2F%2Fwww.instagram.com%2Fp%2FCGIq8o7B2Jm%2F](https://iframely.com/embed/https%3A%2F%2Fwww.instagram.com%2Fp%2FCGIq8o7B2Jm%2F)

**Comment by iparamonau** [comment]
@luminous8 please reach out to cloud support as this seems to be something unique to your account. For my developer account, Iframely cloud returns 1080 wide images for your URLs above.

**Comment by j-r-t** [comment]
@iparamonau Facebook now returning this odd lookaside url for the thumbnail - only just started happening, is there any fix for it? 

thanks

**Comment by iparamonau** [comment]
Suppose everyone affected has now migrated and closing the ticket for good.
