### ISSUE TITLE
TikTok urls not working

### ISSUE THREAD

**Issue by wiemann** [itteco/iframely#287]
Oembed directly against tiktok server works [https://www.tiktok.com/oembed?url=https://www.tiktok.com/@fitdadceo/video/6874569665834650886](https://www.tiktok.com/oembed?url=https://www.tiktok.com/@fitdadceo/video/6874569665834650886`)

but iframely returns: 
`415 - error - {"error":{"source":"iframely","code":415,"message":"Requested page error: 415"}}`

**Comment by iparamonau** [comment]
The URL `https://www.tiktok.com/oembed?url=https://www.tiktok.com/@fitdadceo/video/6874569665834650886` fetches a JSON response. 

Iframely requires text/html URLs. Like this one - `https://www.tiktok.com/@fitdadceo/video/6874569665834650886` - which works well.
