### ISSUE TITLE
Extra div tag in the html element in iframely and oembed API response

### ISSUE THREAD

**Issue by deshetti** [itteco/iframely#289]
I am running the version 1.5.0 of iframely and see that there is an extra  `<div>` tag wrapped around the HTML in the API response for iframely and oembed end points.

Here is the response field for eg:
```
"html": "<div><div style=\"left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;\"><iframe src=\"https://www.youtube.com/embed/6tz1_znrbmc?start=66\" style=\"border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;\" allowfullscreen scrolling=\"no\" allow=\"encrypted-media\"></iframe></div></div>"
```

Is this the expected behavior because I that is not the same with the API response in the paid version of iframely:

```
"html": "<div style=\"left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;\"><iframe src=\"https://www.youtube.com/embed/6tz1_znrbmc?rel=0&amp;start=66\" style=\"border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;\" allowfullscreen scrolling=\"no\" allow=\"encrypted-media; accelerometer; clipboard-write; gyroscope; picture-in-picture\"></iframe></div>"
```

**Comment by deshetti** [comment]
Checking to see if anyone would be able to shed light on this one? Is it expected to have an extra <div> wrapped around the HTML response? Like I pointed out the response is different b/w the open-source and the paid versions.

**Comment by iparamonau** [comment]
That is the legacy div that is meant to regulate max-width when required. We've fixed it in the cloud when we were adding it unnecessarily. We'll be porting the fix to the self-hosted version soon.

**Comment by nleush** [comment]
Fixed in https://github.com/itteco/iframely/commit/80bb6511d674b2c41988a3438e145c94b8c25c75 on `develop` branch.

Now maximum width wrapper will be placed only if required. Option can be changed by `CONFIG.FORCE_WIDTH_LIMIT_CONTAINER` which is `false` by default.
