### ISSUE TITLE
Iframely Debugger Blocks ngrok

### ISSUE THREAD

**Issue by jamesward** [itteco/iframely#291]
http://debug.iframely.com/ blocks access to *.ngrok.io which makes debugging really hard.  Can you suggest an alternative or resolve this?

**Comment by iparamonau** [comment]
ngrok is indeed blocked due to previous abuse. Iframely cloud and debugger only work with the public resources. You'd need to publish your resources to the internet before our debugger can recognize it. Heroku, App Engine, or even S3 - would all be supported.
