### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by deshetti** [itteco/iframely#299]
Is there a health check endpoint for iframely? If not, would it be helpful to setup one?

**Comment by iparamonau** [comment]
Thanks for the suggestion. What would be the use-case for this healthcheck?

Internally, we use simple API requests as external health checks in reverse proxies and DNS balancers. For the internal health, there's a monitor of memory/cpu usage it's possible to restart the node cluster as configured in your local config.
