### ISSUE TITLE
Twitter image previews?

### ISSUE THREAD

**Issue by dessalines** [itteco/iframely#301]
I notice that iframely doesn't have image previews for twitter, only the html text blurbs, and the description. Is there any way to get these working?

**Comment by iparamonau** [comment]
It depends on the URLs. Do you mean for statuses or user profiles?

**Comment by dessalines** [comment]
The pictures on statuses, example: https://twitter.com/ANTICONQUISTA/status/1326605304021229568. I'm trying to [implement this in lemmy](https://enterprise.lemmy.ml/post/66), but I see Iframely is only able to get the title, and embed_html.

I know it has to work somehow, because I see these lead images when they're posted in discord chats.

**Comment by iparamonau** [comment]
Unfortunately it looks like Twitter has removed the thumbnail images from the public access. They probably whitelist user-agents as the requests with Discord's one give thumbnails alright. You can configure it in `PROXY` section of your local config. See the config example file for spec.

**Comment by dessalines** [comment]
Thanks. If anyone sees this and has a hack / way to get those working I'd be happy to know how to do.
