### ISSUE TITLE
iframely started returning 400s for twitter urls

### ISSUE THREAD

**Issue by tombburnell** [itteco/iframely#312]
http://iframely:8080/oembed?url=https://twitter.com/ScotchWhiskySWA/status/1339541248584130560?ref_src=twsrc%5Etfw

{
  "error": {
  "source": "iframely",  
  "code": 400,
  "message": "Bad Request: Requested page error: 400"
  }
}

Is this an twitter api change that iframely doesn't support?

**Comment by tombburnell** [comment]
Hi, I see you have added an error handler. Would pulling this change fix the errors we are seeing or does it just make it look nicer? Do you know if these 400s are due to an issue at Twitter? We have seen a sudden big increase in the last 48 hrs.
Thanks, Tom

**Comment by Thomas-Negrault** [comment]
I tracked down the issue to the user agent, with the iframely user agent I got this response when trying to crawl a twitter link:
![image](https://user-images.githubusercontent.com/6841201/102599233-7bb13480-411d-11eb-92e0-06c083b6c32e.png)

I "fixed" it by setting this config:

`USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1) AppleWebKit/537.36`

**Comment by tombburnell** [comment]
Great thanks - we'll give that a go.

**Comment by iparamonau** [comment]
This should now be resolved in `develop`. We can't fix 400 for you, obviously, but there's a fallback to oEmbed-only in place now.

**Comment by tombburnell** [comment]
Hi, the change seems to be working for us so thank you. 

For my understanding, is this happening for all calls to twitter or just the fallback? 

We currently have a consumer key and access token set for twitter - so I would expect iframely to be using the API? Why would the api care what the user-agent is? Does this mean we are not configured correctly?

Example log here:

[20-12-21 11:09:18]:44075 10.250.132.211, 10.250.133.19 - Loading /oembed for https://twitter.com/DHSCgovuk/status/1340930003282894849?ref_src=twsrc%5Etfw
[20-12-21 11:09:18]:44075    -- plugin response: {"plugin":"htmlparser","response":400,"uri":"https://twitter.com"}
[20-12-21 11:09:18]:44075    -- plugin response: {"plugin":"htmlparser","response":400,"uri":"https://twitter.com/DHSCgovuk/status/1340930003282894849?ref_src=twsrc%5Etfw"}
Requested page error: 400

**Comment by iparamonau** [comment]
The plugin tries to avoid making http requests to their status pages. But if it sees a picture in the tweet's text, it tries to activate meta parser as well for that.  [Code](https://github.com/itteco/iframely/blob/master/plugins/domains/twitter.com/twitter.status.js#L170-L171)

We should probably add a switch to disable that completely if you don't need it. But in any case, the HTTP 400 and 429 errors should now be just ignored.

**Comment by tombburnell** [comment]
We can't ignore the 400s (or 429s) - they cause failures and thus tweets are not appearing on our site.

Some questions:

1) For clarification, are you saying :
- even though we have a api key set, it's going to the public website rather than the api to get the image details
- therefore we are getting 400s when there is an image in the tweet

2) What does your handler patch #313 do? does it prevent the 400 if can't fetch the image data?

3) What does the meta-parser fetch for the image? Almost certainly we don't need this if it doesn't impact the html so a mechanism to disable would be good for us.

4) The twitter status mentions the following headers:  x-concurrent-job-limit,  x-concurrent-job-limit-remaining, x-rate-limit-limit, x-rate-limit-remaining,  x-rate-limit-reset.  If we are getting 400s, are we hitting any of these rate limits?

Thanks, Tom

**Comment by iparamonau** [comment]
> they cause failures and thus tweets are not appearing on our site.

Is it still the case? The patch in #313 was meant to silence the HTTP errors. And yes, the errors were only for tweets with images. We'll add a flag to disable it. Twitter seems to be blocking by user-agent these days, so no `x-` headers are in play

**Comment by tombburnell** [comment]
I see - that's part of what I wanted to confirm in Q3. 

When will you be putting that patch into master/production?

**Comment by iparamonau** [comment]
It's already in master and in NPM as v 1.6.0

**Comment by tombburnell** [comment]
ok great - thanks - and thanks for the quick responses and quick patching
