### ISSUE TITLE
Support reddit embeds

### ISSUE THREAD

**Issue by nivekuil** [itteco/iframely#323]
Hi, thanks for maintaining iframely. I notice that iframely has recently begun picking up players from reddit embeds, e.g. https://iframely.com/embed/https%3A%2F%2Fv.redd.it%2Ftzkw2ln2z7f61?media=1 but the aspect ratio is fixed to 16:9 and only the autoplay version is returned. Not sure where you're supposed to get the canonical embed code, but the iframes do have a "watch on reddit" button (visible when the aspect ratio isn't cut off) so it seems that these are meant to be public.

**Comment by iparamonau** [comment]
You're choosing &media=1 "just the player" option. By default, [we give](https://iframely.com/embed/https%3A%2F%2Fv.redd.it%2Ftzkw2ln2z7f61) Reddit's canonical embed code. Albeit, the video their has the same aspect ratio. It is actually a ratio in their video stream, so cannot really change that.
