### ISSUE TITLE
Vulnerability in ejs

### ISSUE THREAD

**Issue by jukatl** [itteco/iframely#325]
Hey there, just writing to inform that the current version of `ejs` in this package has a security vulnerability: https://sca.analysiscenter.veracode.com/vulnerability-database/security/os-command-injection/javascript/sid-29384

This was patched in `3.1.6` of `ejs` https://github.com/mde/ejs/commit/abaee2be937236b1b8da9a1f55096c17dda905fd

If any help is needed in writing a PR to bump this, let me know. I did a small demo and ran the tests, and they all seemed to pass fine when it was bumped up (even though it's a major version change)

**Comment by nleush** [comment]
Fixed in https://github.com/itteco/iframely/commit/504b14352cbce6273684db1d576cabf2c39c3eec#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
