### ISSUE TITLE
Does iframely support facebook's  "Ombed read". Facebook tell us that oembed will be deprecated soon

### ISSUE THREAD

**Issue by tombburnell** [itteco/iframely#338]
Hi, we received this message from facebook recently:

The oEmbed product has been replaced with the oEmbed Read feature. If you implemented the oEmbed product before June 8, 2021, you have until September 7, 2021 to complete App Review for the oEmbed Read feature. If you have not been approved for the oEmbed Read feature by September 7, 2021, your oEmbed implementations will fail to load.

Do you know if this will this impact our facebook embeds using iframely?

**Comment by iparamonau** [comment]
The integration stays the same, it's the same access token. The ACL restrictions are purely on Facebook's end. Otherwise they haven't changed the APIs themselves.

**Comment by tombburnell** [comment]
Hi, thanks for getting back quickly. That's great to hear. 
Do you know if we have to authorise anything specifically for the user that our token is registered to?

**Comment by iparamonau** [comment]
You'd need to pass the app review for the feature, yes. The message from Facebook has all those details. Just follow their instructions.
