### ISSUE TITLE
Issue with embedding Facebook page

### ISSUE THREAD

**Issue by hondem** [itteco/iframely#339]
Hello. Recently we ran into an issue with embedding Facebook page (for example https://www.facebook.com/ZaujimavySvet). We have the self-hosted instance running in Azure (server situated in Holland) and then there is my localhost instance (Czech Republic). Both are running exactly the same Docker image with exactly the same environment variables and API keys. 

Our Facebook API key has `oembed_read` approved. Let's see the results:

Requesting `http://localhost:8061/iframely?url=https://www.facebook.com/ZaujimavySvet` results successfully in embedding-ready data:
```
{
  "meta": {
    "site": "Facebook",
    "canonical": "https://www.facebook.com/ZaujimavySvet/",
    "description": "Zaujímavý Svet, Bratislava. 176 710 To se mi líbí · Mluví o tom (2 598). Svet je krásny, pestrý a plný emócií . Objavujte ho aj vďaka našej stránke",
    "title": "Zaujímavý Svet"
  },
  "links": {...},
  "rel": [...],
  "html": "<div id=\"fb-root\"></div>\n<script async=\"1\" defer=\"1\" crossorigin=\"anonymous\" 
  src=\"https://connect.facebook.net/cs_CZ/sdk.js#xfbml=1&amp;version=v11.0\" nonce=\"LLqqAJb0\"></script><div 
  class=\"fb-page\" data-href=\"https://www.facebook.com/ZaujimavySvet\" data-small-header=\"\" data-adapt-container- 
  width=\"1\" data-hide-cover=\"\" data-show-facepile=\"\" data-show-posts=\"\" data-width=\"600\"><blockquote 
  cite=\"https://www.facebook.com/ZaujimavySvet\" class=\"fb-xfbml-parse-ignore\"><a 
  href=\"https://www.facebook.com/ZaujimavySvet\">Zaujímavý Svet</a></blockquote></div>",
  "options": {...}
}
```

However when I try to request exactly the same url on my cloud instance, i get this:

```
{
  "meta": {
    "canonical": "https://www.facebook.com/login/web/"
  },
  "links": {
    "icon": [
      {
        "href": "https://www.facebook.com/favicon.ico",
        "type": "image/icon",
        "rel": [
          "icon",
          "iframely",
          "ssl"
        ]
      }
    ]
  },
  "messages": [
    "Facebook profile pages of individual users are not embeddable."
  ],
  "rel": []
}
```

Am I missing something? Why embedding works on localhost and not in production environment? Do I have to set some settings in my developers account?

**Comment by itarcontact** [comment]
Hello.
I have a similar problem with Facebook pages. In this case I have the following response every time:

`messages":["Unowned Facebook Pages are not supported."]`

Does anyone also have a similar problem?

**Comment by itarcontact** [comment]
@hondem did you find the solution for production environment?

**Comment by iparamonau** [comment]
Error handling for FB pages should now be fixed.
