### ISSUE TITLE
Started getting 429's for broken instagram links.

### ISSUE THREAD

**Issue by tombburnell** [itteco/iframely#345]
Hi , In the last week or so, we've started getting 429 responses for instagram embeds. In each case, we think it appears to be an invalid embed from one of our users. But it's odd to be a 429 rather than 400/500.  

Loading /oembed for https://www.instagram.com/banksy/
    -- plugin redirect (by "htmlparser") https://www.instagram.com/accounts/login/
    -- plugin response: {"plugin":"htmlparser","response":429,"uri":"https://www.instagram.com/accounts/login/"}
Requested page error: 429

429 normally means too many requests/exceeded quota etc. but we seem to be getting successful requests at almost the same time for normal embeds.

Loading /oembed for https://www.instagram.com/p/CTsnbjbPru3/
 -- plugin redirect (by "htmlparser") https://www.instagram.com/accounts/login/

Do you know if instagram have changed something recently?

Thanks, Tom

**Comment by iparamonau** [comment]
Is it just for Instagram profiles? Most social networks these days protect their profile pages. if you check that URL at iframely.com, you'll see that our cloud explicitly rejects Instagram profiles:
`Instagram profiles can no longer be supported, sorry.`

**Comment by iparamonau** [comment]
The error handling for Instagram should now be improved and 429 should not be happening on posts. Profiles, as explained, can not be longer be supported.
