### ISSUE TITLE
Version 2.0.0 - BREAKING CHANGES. Migration steps

### ISSUE THREAD

**Issue by iparamonau** [itteco/iframely#350]
Iframely is finally upgraded to the current node versions #344. Due to significant changes in the Node itself, there is sadly no backward compatibility. 

**The minimum version of the Node required for Iframely starting from version 2.0.0 is Node 12.**

The good news is that we used this version in our cloud for a few months now, and it is proved stable.

Here's the migration checklist if you used Iframely with version less than 12:

- [ ] Update Node to versions from 12 to 16 (you may also experiment with 17).
- [ ] ECMAScript modules [are enabled](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling) in Node 13+. If you have any custom plugins or custom code for Iframely, you'll likely need to refactor your code to `import` statements.
- [ ] Use `import` if you plug Iframely as the node module.
- [ ] Update your local config file to proper packaging. See `config.local.js.EXAMPLE`
- [ ] If you used proxies, see #354 
- [ ] If you use Docker, we need your help. Docker has always been community-contributed, and we'll likely need pull requests to update it.
- [ ] Check and verify an upgrade on staging before venturing into production.
- [ ] Please post your migration questions below to this issue.

Other significant change in 2.0.0 is the absence of `request` module, which was deprecated a while ago. We now rely on [adobe/helix-fetch](https://github.com/adobe/helix-fetch) module, which we verified as being most production-ready among available alternatives. If you used `request` variable in your custom plugin methods, you'd need to test them with special attention. 

If you used Iframely with Node 12, it is likely that you have had HTTP/2 disabled due to #277. It is now resolved and HTTP/2 is enabled for all deployments. The system feature flag to turn it off is no longer available, but you can configure it as a proxy element.

UPDATE: Proxy is still available, albeit with a simple workaround echo service configured as `CONFIG.PROXY_URL`. See #354 (and we'll update example config soon)

**Comment by iparamonau** [comment]
UPDATE: We missed to mention about changes in the proxy support. Proxy is still available, albeit with a simple workaround echo service configured as CONFIG.PROXY_URL. See #354 (and we'll update example config soon)

**Comment by diskortsev** [comment]
FYI, iframely with pm2 failed to start with node 12 at Debian 11. 
`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/www/iframely/server.js`

With node 14 it started without any problems.
