### ISSUE TITLE
Missing meta description, site, author and date

### ISSUE THREAD

**Issue by JohnRock0422** [itteco/iframely#362]
Refer to attached screens,

**IFramely cloud** returns more information.
![Screenshot1 (1)](https://user-images.githubusercontent.com/26728661/160367144-3a37f28c-62f7-4aeb-a922-6c8718c0fdf8.png)

But **IFramely self-hosted** only show title and canonical
![Screenshot1 (2)](https://user-images.githubusercontent.com/26728661/160367137-739934a3-9501-4f17-90a6-9ab4492b1906.png)

Using this docker image
catablog/iframely:latest

**Comment by iparamonau** [comment]
Try to `curl https://en.wikipedia.org/wiki/Cat`. There should be the open graph section in response as this:

````
<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Cat_poster_1.jpg/640px-Cat_poster_1.jpg"/>
<meta property="og:image:width" content="640"/>
<meta property="og:image:height" content="420"/>
<meta property="og:title" content="Cat - Wikipedia"/>
<meta property="og:type" content="website"/>
```

If your server doesn't get that information from Wikipedia, there's unfortunately little our open-source version can do to help.

**Comment by iparamonau** [comment]
I see now that your local version does have the images and title from Wikipedia's Open Graph. So all is good.

Description and date comes from cloud's private plugin. It isn't included into the open-source version. See what else isn't included [here](https://github.com/itteco/iframely#not-included-as-compared-to-cloud-api)

**Comment by JohnRock0422** [comment]
Thanks your reply.

Would I have any hints or beginner guide about how to develop such plugin myself?
