### ISSUE TITLE
Missing attributes for Spotify embeds

### ISSUE THREAD

**Issue by sushantbs** [itteco/iframely#405]
Hey there,

I am Sushant and I work at Spotify. We have noticed that when Spotify embeds are rendered via Iframerly the links within the embeds do not work (probably because the `<iframe>` element does not have the `allow-popups` in the `sandbox` attribute?). 

Additionally, Spotify embeds often play encrypted content which require EME to be enabled, for which the `<iframe>` element in oEmbed response also contains the `encrypted-media` attribute but when served via Iframerly this attribute is missing, making a lot of our content unplayable via Iframerly. 

It would be great if our users could have the full embed experience when the embeds are served via Iframerly, so please let us know if we can do anything from our end to make this happen. Thanks!

**Comment by iparamonau** [comment]
Thanks for reporting. We do not actually set any sandbox attributes on iFrames, but our users may opt to add it themselves. 

As for the `encrypted-media` - this issue should be fixed as of yesterday.

**Comment by sushantbs** [comment]
Thanks for the quick response @iparamonau
