### ISSUE TITLE
Batch querying by content IDs does not work

### ISSUE THREAD

**Issue by kowpatryk** [itteco/iframely#412]
Currently, when querying iframely API by multiple content IDs using `iframe.ly/{ID1}-{ID2}-...-{IDn}.json` [format](https://iframely.com/docs/ids#batch-request-up-to-100-ids), the following response is returned:

```json
{
    "[object Object]": {
        "status": 404,
        "error": "link not found"
    }
}
```

I have used the example from documentation (http://iframe.ly/qH98az-7QPpxhS.json), I have also tried with some of IDs generated after calling the API with `url` param and `id=1` (the plan supports content IDs) - the same response is returned.

**Comment by nleush** [comment]
Thanks for your feedback! It is now fixed.
