### ISSUE TITLE
Intermittent issues with Google share links

### ISSUE THREAD

**Issue by acrokat** [itteco/iframely#426]
We've run into a few issues intermittently with Google workspace links. I haven't been able to identify a consistent repro, but outlined the general behavior is outlined below

### Behavior
1. Use the "Share" button and set access to Public edit on a Google doc 
2. Plug it in the iframerly url checker
3. The full URL with the `?usp=share `parameter will 403
4. Removing the share param will embed as expected

It seems to happen with specific one off docs

**Comment by iparamonau** [comment]
Thank you. Is there a chance you could provide a link to such specific one off doc for us to try and reproduce the issue?

**Comment by acrokat** [comment]
@iparamonau apologies, missed this! the cases i was running into it with were internal companydocs, i tried a few times to repro with a random test doc without success. will let you know if i have a shareable doc with a repro!

**Comment by DiegoGW** [comment]
Hi @iparamonau ! We managed to replicate this issue with the following spreadsheet: https://docs.google.com/spreadsheets/d/1cDh1hI060rwPXG59tidB1skvCYkZrM6kayTX6nT105E/edit?usp=sharing

Let us know if you need more details to continue your research.

Thanks!

**Comment by iparamonau** [comment]
That URL seems to be working alright [for us](https://iframely.com/try?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1cDh1hI060rwPXG59tidB1skvCYkZrM6kayTX6nT105E%2Fedit%3Fusp%3Dsharing). 

In this case, it may be some issue with Google's cache state. We'll try again in a while.

**Comment by iparamonau** [comment]
I am going to close this old issue because it doesn't seem we're able to help more.
