### ISSUE TITLE
Inspect Network Calls

### ISSUE THREAD

**Issue by thatvegandev** [itteco/iframely#451]
Is there any way to log the details of outgoing network requests iframely makes to different providers? I'd like to gut check that parameters I'm settings are in fact making their way to the providers

**Comment by iparamonau** [comment]
There is such log within Iframely. Perhaps, you could use some external tool to track that on your computer. 

Or add some logging to your local Iframely copy `request_options` before [this block](https://github.com/itteco/iframely/blob/master/lib/utils.js#L174-L189)
