### ISSUE TITLE
NODE_ENV=development and config.local.js

### ISSUE THREAD

**Issue by kulakowka** [itteco/iframely#47]
I ask you to make changes to the documentation. (https://iframely.com/docs/host).

I have a NODE_ENV==='development' and when i created `config.local.js` file, this does not work. Then when i created file `config.development.js` - it's work!

I think it's not obvious.

I think you should specify that the name of the config file depends on the environment (NODE_ENV).

P.S. Sorry about my english.

**Comment by iparamonau** [comment]
Thanks Anton, will do.
