### ISSUE TITLE
Issue with a long html page without javascripts.

### ISSUE THREAD

**Issue by alieneby** [itteco/iframely#481]
This is the URL, which iFramely can not handle. 
It is a simple page, but very long.
https://horn.alien.de/erdbeben.php#511
Perhaps you want to know about these things...

**Comment by iparamonau** [comment]
Thanks for reporting. Do you mind sharing what the error is? The local instance with the default config, as well as all our cloud version seem to handle that URL alright: 
http://debug.iframely.com/?uri=https%3A%2F%2Fhorn.alien.de%2Ferdbeben.php%23511

(that debugger is based on a copy of this very repo)

**Comment by alieneby** [comment]
Thank you for the feedback.

Sometimes it works. I have cloned your repository without any modifications even the config.js is unchanged. 

The log:
Loading /iframely for https://horn.alien.de/erdbeben.php?2#513
Loading /iframely for https://horn.alien.de/erdbeben.php?2#513
 -- plugin response: {"plugin":"meta","response":"timeout","uri":"https://horn.alien.de/erdbeben.php?2#513"}
Processing error: timeout

I guess I only have to change RESPONSE_TIMEOUT in config.local.js 

Thank you.
