### ISSUE TITLE
Caching fails on jsonp requests

### ISSUE THREAD

**Issue by shyamster** [itteco/iframely#49]
Upgrading an older install of iframely, I noticed that caching was no longer working for jsonp requests.  Haven't looked into the code yet, but checking keys in Redis, I see keys like these:

```
urlcache:0.5.7:/oembed?callback=jQuery11020026020831894129515_1424903544378&url=http%3A%2F%2Fwww.slideshare.net%2Fcmcnulty2000%2Flavacon-session-proposal-triple-tag-managed-metadata-and-taxonomies-for-content-management&_=1424903544379
```

which includes the jquery callback function which can obviously change with each request.  Should caching be rather done with a key like this?

```
urlcache:0.5.7:oembed:http%3A%2F%2Fwww.slideshare.net%2Fcmcnulty2000%2Flavacon-session-proposal-triple-tag-managed-metadata-and-taxonomies-for-content-management
```

**Comment by iparamonau** [comment]
Oops. Yes, since we added more params to the API calls, the previous key won't work either. 
@nleush will port the fix from our cloud api into the open-source version.

**Comment by shyamster** [comment]
Thanks @iparamonau - the way it is right now, the cache is full of keys that never has a chance of getting used taking up valuable cache memory

**Comment by iparamonau** [comment]
@shyamster yes, sorry about this. We are just pushing a big release for the cloud and will then quickly prepare a new version of Iframely parsers too.

**Comment by iparamonau** [comment]
Iframely version 0.8.0 is now released and is available in master branch. Heads up if your Node is < 0.10.22: https://iframely.com/whatsnew
