### ISSUE TITLE
remove racially loaded terms from the website

### ISSUE THREAD

**Issue by zerwes** [itteco/iframely#491]
see https://iframely.com/docs/about#allow-iframely-robot-on-your-network:

> ... please add Iframely to your whitelist ...
> ... Whitelist all of our public IP addresses ...

Please consider using no inflammatory jargon.
Use *allowlist*, not ~whitelist~, and *blocklist*, not ~blacklist~ ...

https://www.bbc.com/news/av/world-us-canada-52988605

**Comment by iparamonau** [comment]
Thank you, fixed. This repo is for the open-source version only. Please report future cloud issues to the support team.
