### ISSUE TITLE
Self-hosted, instagram embed, redirect loop.

### ISSUE THREAD

**Issue by freakst** [itteco/iframely#503]
Since 4 days ago, instagram and twitter falls into redirect loop. Latest commit (~20h) ago fixed twitter for me, but not instagram, receiving tonns of: 
`-- pid:3976    -- Following redirect from https://www.instagram.com/login/?next=https%3A%2F%2Fwww.instagram.com%2Flogin%2F%3Fnext%3Dhttps%253A%252F%252Fwww.instagram.com%252Flogin%252F%253Fnext%253Dhttps%25253A%25252F%25252Fwww.instagram.com%25252Flogin%25252F%25253Fnext%25253Dhttps%2525253A%2525252F%2525252Fwww.instagram.com%2525252Flogin%2525252F%2525253Fnext%2525253Dhttps%252525253A%252525252F%252525252Fwww.instagram.com%252525252Flogin%252525252F%252525253Fnext%252525253Dhttps%25252525253A%25252525252F%25252525252Fwww.instagram.com%25252525252Flogin%25252525252F%25252525253Fnext%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fwww.instagram.com%2525252525252Flogin%2525252525252F%2525252525253Fnext%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fwww.instagram.com%252525252525252Fp%252525252525252FCBsxHGtjD_4%252525252525252F to https://www.instagram.com/login/?next=https%3A%2F%2Fwww.instagram.com%2Flogin%2F%3Fnext%3Dhttps%253A%252F%252Fwww.instagram.com%252Flogin%252F%253Fnext%253Dhttps%25253A%25252F%25252Fwww.instagram.com%25252Flogin%25252F%25253Fnext%25253Dhttps%2525253A%2525252F%2525252Fwww.instagram.com%2525252Flogin%2525252F%2525253Fnext%2525253Dhttps%252525253A%252525252F%252525252Fwww.instagram.com%252525252Flogin%252525252F%252525253Fnext%252525253Dhttps%25252525253A%25252525252F%25252525252Fwww.instagram.com%25252525252Flogin%25252525252F%25252525253Fnext%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fwww.instagram.com%2525252525252Flogin%2525252525252F%2525252525253Fnext%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fwww.instagram.com%252525252525252Flogin%252525252525252F%252525252525253Fnext%252525252525253Dhttps%25252525252525253A%25252525252525252F%25252525252525252Fwww.instagram.com%25252525252525252Fp%25252525252525252FCBsxHGtjD_4%25252525252525252F`

**Comment by iparamonau** [comment]
Do I get it right that you're requesting the log messages to be removed as too verbose?

**Comment by freakst** [comment]
Not really. We've been running fine, until couple days ago, when suddenly twitter and insta stopped working and fell into and error loops, both redirecting (we use app for insta with access token which is valid and returns embeds from within the iframely container we run in k8s with curl). Iframely though spits tonns of above for every requrest and just times out for insta. 
Twitter got fixed  by one of the latest patches. 

```
/iframely $ wget -O - "http://localhost:8061/oembed?url=https://www.instagram.com/p/CsIoTd8tYMW/"
Connecting to localhost:8061 (127.0.0.1:8061)
wget: server returned error: HTTP/1.1 408 Request Timeout
```

**Comment by freakst** [comment]
@iparamonau I've tested this, It has the same effect.

**Comment by iparamonau** [comment]
@freakst was it the full version from the `main`, or the cherry-picked commit? If the main version still doesn't work for you, please send over your entire `config.local.js` file to support at iframely dot com.

**Comment by freakst** [comment]
I have tried bot, the pr and the latest main, just tonight. Sendind config.js.

**Comment by freakst** [comment]
So just an hour ago it started working. Magically. I have a hypothesis that facebook induced some kind of ban because of the avalanche of redirects first. And because I've deployed `fixed` version, you supplied me yesterday the ban decayed?

**Comment by iparamonau** [comment]
You might still be experiencing a few redirects, we log it now only when there is `DEBUG: true` in your config. The redirect error should have been ignored and the HTML embed codes should have worked after the last patch. My guess is your deployment did not apply the fix for some reason, and now did apply it alright the second time. I'll close for now. Please feel free to add more input.
