### ISSUE TITLE
cannot parse medium article

### ISSUE THREAD

**Issue by ches4117** [itteco/iframely#514]
I have tried parsing several Medium articles, but they all returned a 403 Forbidden error.

test url: https://medium.com/next-generation-web/create-a-dark-mode-toggle-micro-interaction-like-a-pro-279305e9c2

<img width="1176" alt="image" src="https://github.com/itteco/iframely/assets/11523578/af1ceb40-a6e7-44cb-95e2-099d0ab725d1">

**Comment by iparamonau** [comment]
Medium turned on the bot protection a couple of weeks ago. We are aware of this, so this issue will need to remain as known issue. Their provider is CloudFlare. Iframely is a recognized/registered robot with CloudFlare. It is the site's owners conscious choice to block us. Our general policy is to respect the publisher's choice.
