### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by theSherwood** [itteco/iframely#515]
Hi. I'm using the iframely package from npm (https://www.npmjs.com/package/iframely) and I see that the last publish was 8 months ago, but there have been a fair few changes since then. Do you have an idea of what the release schedule will look like going forward? I'd like to contribute a fix, but the release history makes it seem like it would be a while before I could make use of it.

**Comment by iparamonau** [comment]
At this point the we push into NPM more or less "on demand". The `main` branch though is the copy of what we have in production ourselves (in fact, we deploy it from `main`). 

But you're right - we should stick to monthly NPM updates, thanks for the nudge. The next update will be on Monday. Please submit your fix and we'll review it.

**Comment by theSherwood** [comment]
I checked about the fix. It looks like the fix is already in the unreleased `main` branch. So once that is released, I should be good to go. Cheers!
