### ISSUE TITLE
Figma app link missing in self-hosted version

### ISSUE THREAD

**Issue by chandruscm** [itteco/iframely#517]
First of all, thanks for open-sourcing this project.

I noticed the embed link for Figma is missing in the iframely API response, it only returns the links to the `thumbnail` and `icon` in the self-hosted version. However, the cloud API includes the `app` embed link. (I'm aware that the cloud API could be using additional domain plugins.)

Upon some investigation, I found out that the entry for Figma in the current whitelist looks like this:
```
// https://iframely.com/qa/whitelist.json

        ...
        "figma.com": {
            "date": 1694741238337,
            "twitter": {
                "player": "deny"
            },
            "oembed": {
                "rich": "deny"
            }
        },
        ...
```

Since `oembed.rich` is set to deny,  the `oembed-rich` plugin is not returning anything.

I tested this by creating a custom whitelist file, with `oembed.rich` set to `["allow"]` for Figma and then the response included the `app` link.

Is `oembed.rich` set to `deny` by mistake for Figma in the whitelist?

Thanks!

**Comment by iparamonau** [comment]
Thank you for reporting. Figma's oEmbed has some issues with URL encoding and therefore we relied on other mechanisms in the cloud. 

The allowlist is now update, Figma's oEmbed now works fine and is enabled for self-hosted versions.
