### ISSUE TITLE
link response header doesn't work

### ISSUE THREAD

**Issue by EchoZhaoH** [itteco/iframely#526]
step
<img width="907" alt="image" src="https://github.com/itteco/iframely/assets/23427655/e454e5f4-5f83-4240-82d4-a2a81a28fccf">
add link response header
 use iframely debug tool
<img width="1290" alt="image" src="https://github.com/itteco/iframely/assets/23427655/1d0979b3-9a8a-4426-8df5-43c911f65157">
doesn't work

**Comment by iparamonau** [comment]
Thank you. The `rel` attribute of oEmbed link should be `alternate`

**Comment by EchoZhaoH** [comment]
hi @iparamonau i tried `rel="alternate"` still doesn't work

**Comment by iparamonau** [comment]
@EchoZhaoH the URL debugger would not show your the oEmbed response?

**Comment by EchoZhaoH** [comment]
@iparamonau yes

**Comment by iparamonau** [comment]
@EchoZhaoH There is currently no oEmbed link at all on your link from the screenshot (https://whiteboard.zoomdev.us/index.html). How can we see the issue?

**Comment by EchoZhaoH** [comment]
hi @iparamonau you can try `curl -I https://whiteboard.zoomdev.us/index.html` to see the response header
and go to the debug tool to test the URL

**Comment by EchoZhaoH** [comment]
@iparamonau this is response header
<img width="941" alt="image" src="https://github.com/itteco/iframely/assets/23427655/33fb4e3a-ab57-4ba3-bbb4-3a97dfff82d9">
and this is iframely debug tool
<img width="1760" alt="image" src="https://github.com/itteco/iframely/assets/23427655/54336833-ab53-46d3-bfc7-31809978cdd7">

**Comment by EchoZhaoH** [comment]
I found it works, did you make any changes? @iparamonau

**Comment by iparamonau** [comment]
The seems to be some state issue with your URL. We probably got the URL cached in transition
https://debug.iframely.com/?uri=https%3A%2F%2Fwhiteboard.zoomdev.us%2Findex.html

**Comment by EchoZhaoH** [comment]
got, thx @iparamonau
