### ISSUE TITLE
Question: Configuring the facebook application correctly

### ISSUE THREAD

**Issue by itarcontact** [itteco/iframely#534]
Hi all,
As everyone knows, in order to properly render content from Facebook, the access_token of the application on FB is required.
To achieve this, the application's access_token in the form of app_id|app_secret and the Oembed Read permission are required. This is all clear!

The essential question is how to properly set everything up in the app on [developers.facebook.com](http://developers.facebook.com/) so that the app passes cyclic FB verification?
I am just at this stage, and Facebook support doesn't want to accept my app because as they write "They have no way to test it".

@iparamonau Can you help? How do you have this resolved in the cloud?

**Comment by iparamonau** [comment]
The best source of this information [Facebook documentation](https://developers.facebook.com/docs/features-reference/oembed-read) and their [App Review guidelines](https://developers.facebook.com/docs/resp-plat-initiatives/app-review)

There are no special instructions from our side beyond linking to Facebook. Their review process follows the internal checklist, and the reviewer needs to tick off all the boxes before they approve your submission. The submission form has all the necessary instructions for this; Iframely's GitHub repo is not the best place for business support. 

You do need to submit your own application for review though, not the self-hosted Iframely version. They need to see how you (and your users) use oEmbed Read in your app, and they are not interested in technical aspects of a library you use to connect to the SDK.

**Comment by itarcontact** [comment]
Thank you very much for your reply.
