### ISSUE TITLE
CNN.com

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#54]
Hi,
The oembed for cnn.com articles is coming out wrong. The type is resulting as "rich", which I believe it should be "link" and the thumbnail url is always coming as CNN logo big image.Like for following article 
"http://edition.cnn.com/2015/04/08/europe/london-hatton-garden-heist/index.html" the oembed is coming as http://iframe.ly/hlUS5x.oembed.

**Comment by iparamonau** [comment]
I grabbed couple links from the CNN's sidebar and they all have different thumbnail, not the logo. 
Perhaps, the editors were a little inattentive in your example. 

Type "rich" is returned for all summary cards that is generated by iframely.com cloud. The self-hosted version will come up as "link".

**Comment by manikmi** [comment]
Looks like something is wrong with the CNN.com. for url http://edition.cnn.com/2015/04/27/asia/nepal-earthquake/index.html, the thumbnail image is shown as http://i2.cdn.turner.com/cnnnext/dam/assets/150425130218-nepal-earthquake-stretcher-large-169.jpg. Even though it is related image, but the image is not shown up on this page. Yeah, I see CNN have added up this image as thumbnail. Actually, I looked at the source for http://edition.cnn.com/2015/04/08/europe/london-hatton-garden-heist/index.html as well. There also the thumbnail image is cnn logo. I think this wrong from CNN side only.

Thanks for the timely response.

**Comment by iparamonau** [comment]
CNN has put it as their Open Graph `og:image` thumbnail, and so we trust it.
