### ISSUE TITLE
Displaying Public Instagram Feeds on a Website Using Self-Hosted Framely

### ISSUE THREAD

**Issue by RyeolRyeol** [itteco/iframely#541]
Hello!
I'm not very familiar with this, but is it okay to use a self-hosted Framely setup to display a public Instagram feed on my website?

**Comment by iparamonau** [comment]
Hi there, Iframely works only with individual post URLs, this includes the self-hosted version. In other words, you'd need to get the list of URLs from a feed somehow first, then send each URL to Iframely separately. This will work both via self-hosted and cloud versions. However, for self-hosted, you'd need to apply for your own oEmbed Read access token from Facebook.

**Comment by RyeolRyeol** [comment]
"If you don't mind, can I ask one more question? I've tried searching, but it's not clear. Is it not possible to embed other users' public posts using Iframely oEmbed, apart from personal posts?"
