### ISSUE TITLE
Loom video embed link missing in self-hosted version

### ISSUE THREAD

**Issue by chandruscm** [itteco/iframely#546]
The iframely API response for Loom video URLs (loom.com) only includes the links to the `thumbnail` and `icon` in the self-hosted version. The cloud API does include the `player` embed link.

I think the entry for loom's `oembed` in the whitelist maybe what's causing this.
```
// https://iframely.com/qa/whitelist.json
      ...
      "loom.com": {
            "date": 1721087741824,
            "twitter": {
                "stream": "deny",
                "player": "deny"
            },
            "og": {
                "video": "deny"
            },
            "oembed": {
                "video": "deny",
                "photo": "allow"
            }
      ...
```

Could you please update the whitelist to allow videos?

Loom test URL: [https://www.loom.com/share/473fad25ebd24b5ea8091503253dfecf](https://www.loom.com/share/473fad25ebd24b5ea8091503253dfecf)

Thanks!

**Comment by iparamonau** [comment]
Thank you for reporting. Loom' twitter player and oembed video have their own issues, we need to keep them denied.

We've [pushed](https://github.com/itteco/iframely/commit/51fcb3f95b5c1e3440dc7cde442fddb9e338b09e) a domain plugin for Loom though that enables the player. It should now be in the main branch.

**Comment by chandruscm** [comment]
Thanks for the quick fix, I appreciate your time!
