### ISSUE TITLE
Issue with nytimes articles

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#55]
Hi,
I am trying to oembed the nytimes articles If i run it on iframely.com/embed it brings back the correct thumbnail image.
But if I take the iframely github repository code and deploy it to my environment, the thumbnail image that I get is the small image using the oembed.

Result from my local
{
  "type": "link",
  "version": "1.0",
  "title": "After He Beat Floyd Mayweather Jr., They Said, O.K., Now Do It Again",
  "author": "John Branch",
  "author_url": "http://topics.nytimes.com/top/reference/timestopics/people/b/john_branch/index.html",
  "description": "When Augie Sanchez, now a top boxing trainer, beat Mayweather in the 1996 Olympic trials, the format was unusual in that it was merely the start of a best-of-three process.",
  "thumbnail_url": "http://static01.nyt.com/images/2015/04/26/sports/26SANCHEZweb1/26SANCHEZweb1-thumbStandard.jpg",
  "favicon": "http://static01.nyt.com/images/icons/ios-ipad-144x144.png",
  "url": "http://www.nytimes.com/2015/04/26/sports/after-he-beat-floyd-mayweather-jr-they-said-ok-now-do-it-again.html"
}

Result from Iframely
{
    "id": "yRtHYy",
    "url": "http://www.nytimes.com/2015/04/26/sports/after-he-beat-floyd-mayweather-jr-they-said-ok-now-do-it-again.html",
    "type": "rich",
    "version": "1.0",
    "title": "After He Beat Floyd Mayweather Jr., They Said, O.K., Now Do It Again",
    "author": "John Branch",
    "author_url": "http://topics.nytimes.com/top/reference/timestopics/people/b/john_branch/index.html",
    "provider_name": "@nytimes",
    "thumbnail_url": "http://static01.nyt.com/images/2015/04/26/sports/26SANCHEZweb1/26SANCHEZweb1-facebookJumbo.jpg",
    "thumbnail_width": 1050,
    "thumbnail_height": 550,
    "html": "<div style=\"max-width: 2100px;\"><div style=\"left: 0px; width: 100%; height: 0px; position: relative; padding-bottom: 52.381%;\"><iframe src=\"//cdn.iframe.ly/yRtHYy?summary=true\" frameborder=\"0\" allowfullscreen=\"true\" webkitallowfullscreen=\"true\" mozallowfullscreen=\"true\" style=\"top: 0px; left: 0px; width: 100%; height: 100%; position: absolute;\"></iframe></div></div>"
}

Is there some thing I am doing wrong and can do to configure Iframely code?

**Comment by iparamonau** [comment]
It looks like you don't have an option to verify and check image sizes in your local config. Thus, Iframely doesn't know the sizes of the thumbnails and selects the first one by default. 

Here's the setting you need to activate to fix it:
https://github.com/itteco/iframely/blob/master/config.local.js.SAMPLE#L96

Beware, it slows down processing a bit since Iframely will go and check sizes of every image (unless sizes are already in cache)

**Comment by manikmi** [comment]
Truly appreciate your timely response. Thanks, it worked.
