### ISSUE TITLE
Iframely is not returning data for Facebook posts consistently

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#56]
Hi,
I noticed that some of the urls for facebook are returning type correctly.
https://www.facebook.com/DBAphotoboothbyAudrey/videos/vb.1479986945578183/1589721204604756
I took the latest code deployed locally it returned bak with type as link, whereas on iframely.com, it returned back as video. either places it did not return the facebook card.

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
FB changed the URL pattern for videos last week. The fix is already in the develop branch, thus the difference. 

We'll also make sure the "status" embeds are given for new video URLs as well.

**Comment by iparamonau** [comment]
This is now be resolved in `develop` branch

**Comment by manikmi** [comment]
Thanks, It worked
