### ISSUE TITLE
type for image sites

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#57]
Hi,
Can we get the type for image sites like flickr, instagram, pinterest, 
to show the media type like photo/video instead of type as rich
and get the thumbnail url?

**Comment by iparamonau** [comment]
Image-only sites should return `photo` type in oembed endpoint. You can check it on Imgur images or, say, 500px, for example.

However, if domains have other embed types, the APIs will give preferences  to those. 

Instagram has status embeds, Flickr has slideshows. Pinterest has only app-like status embeds. Hence, the preference in oEmbed endpoint. oEmbed is a little limited as a format as it only allows one embed type and we give preference to rich one. 

Iframely format should return all available rels.

The same is true for Instagram videos - the preference is given for status embeds. 

In the cloud, if you request with `&iframe=1`, the preference will be given to more simple types: photos and plain videos. 

We'll think and perhaps give and iframe option to open source version as well.

**Comment by manikmi** [comment]
Thanks,

Truly appreciate if you could help.

**Comment by iparamonau** [comment]
Sorry for taking so long to comment. I completely forgot we actually have your issue covered already.

Just re-define [OEMBED_RELS_PRIORITY](https://github.com/itteco/iframely/blob/master/config.js#L159) in your local config file, put image first, and will use your preference, oEmbed API will return images in `html` field, if Iframely has any.

**Comment by manikmi** [comment]
Hi Ivan

Is there a way to get the flickr photos(with thumbnail) and videos(with html code) return as type photo and video only. Right now it returns as type rich. I tried removing the apikey from config.local.js, it started showing photos as type photo and video as type rich. Also, my concern is if I remove the apikey, it should not return the rate limit issues?

Regards,
Manik Mittal
