### ISSUE TITLE
Right way to test plugins?

### ISSUE THREAD

**Issue by somebody32** [itteco/iframely#58]
Hi!

I'm trying to a create a new plugin and failing with running current test suite. Looks like there are 2 different commands for that:

* `npm test` (runs less than 10 tests)
* `./test-plugins.sh` (fails because of CONFIG.tests settings not specified. I've tried to provide them, but then scripts hangs doing nothing)

Sorry if I missed some docs, but what is the right way to run the tests now?

**Comment by nleush** [comment]
Hi.

You can find sample tests config here: https://github.com/itteco/iframely/blob/master/config.local.js.SAMPLE#L61

To make test on specific plugin you can run: `sh test-plugins.sh facebook.post`

To make plugin tests work you have to specify `tests` attribute of plugin (look examples in existing plugins).

Test results shown in `/tests` page when running iframely as server.

**Comment by somebody32** [comment]
@nleush thank you for the answer! Working now

**Comment by nleush** [comment]
By the way. Best way to test one plugin when developing - test it manually using debugger on server `localhost:8061/debug`. There is a lot of information to understand bugs.

Batch testing needed when checking all plugins.
