### ISSUE TITLE
Flickr image is being returned as of type video

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#59]
Hi,

The flickr image with url https://www.flickr.com/photos/immaterialgirl/8659417790/in/photostream/
is returned as of type video on open source code. Even though I have entered the apiKey for flickr in config.local.js. What can be missing?

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
The issue and explanation here is the same as in #57. 

If you'll go to your local debug tool or check /iframely endpoint JSON response, you'll see all available media. 

http://localhost:8061/debug?uri=https%3A%2F%2Fwww.flickr.com%2Fphotos%2Fimmaterialgirl%2F8659417790%2Fin%2Fphotostream%2F

**Comment by manikmi** [comment]
Yes, I can see all the available media. but the meta/media is returned as "player" and the rel is returning "player", so oembed end point is returning it as video. The issue is with type returned wrongly in oembed end point.

**Comment by iparamonau** [comment]
I see. We should have had a separate rel for slideshows, this way it could be translated into `rich` oembed type instead of `video`. But for now, it appears to make things more complex rather then simplifying it. So slideshows go as player for the time being.
