### ISSUE TITLE
div tag with html

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#60]
Hi,
It is not an issue, just a question. Is there a way to get the html with the div tag for video/rich embeds. Like for youtube embeds. I get html as 

"<div style=\"left: 0px; width: 100%; height: 0px; position: relative; padding-bottom: 75.0019%;\"><iframe src=\"https://www.youtube.com/embed/uyV1fsIGJKo?rel=0&amp;showinfo=1\" frameborder=\"0\" allowfullscreen=\"true\" webkitallowfullscreen=\"true\" mozallowfullscreen=\"true\" style=\"top: 0px; left: 0px; width: 100%; height: 100%; position: absolute;\"></iframe></div>"

I want only the iframe/video tag.

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
This wrapper is what makes the embeds responsive. It can not be removed from HTML itself. However, if you use /iframely JSON endpoint, the iframe source will be given as `href` attribute of the `player` link.
