### ISSUE TITLE
npr.org embeds are not working...

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#63]
I tried to embed the link:

http://www.npr.org/2014/12/06/368714299/first-generation-boston-girl-becomes-career-woman-in-diamants-latest

on npr.org, they mentioned the embed code as:

<embed src="http://www.npr.org/v2/?i=368714299&#38;m=368931763&#38;t=audio" height="386" wmode="opaque" allowfullscreen="true" width="400" base="http://www.npr.org" type="application/x-shockwave-flash"></embed>

Is there a way to get the npr.org embed using open source code?

Thanks,
Manik Mittal

**Comment by iparamonau** [comment]
NPR only offers their embed codes for manual copy-paste. And we don't have specific domain parser for them yet. But feel free to submit a PR :)

**Comment by manikmi** [comment]
Hi Ivan,

I would be really happy to contribute. Can you please give me some pointers how to start writing a domain parser?

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
The unfinished description is in [WRITE-A-PLUGIN.md](https://github.com/itteco/iframely/blob/master/docs/WRITE-A-PLUGIN.md). Should give sufficient intro though

**Comment by iparamonau** [comment]
The support for direct links to players is now in dev branch.

**Comment by canvasmanager** [comment]
Can you give me some sample direct link?

**Comment by iparamonau** [comment]
Once you click on "Listen to the story" on inlined player [in the article](http://www.npr.org/2014/12/06/368714299/first-generation-boston-girl-becomes-career-woman-in-diamants-latest), it opens a pop-up player. 

Take URL from address bar in this pop-up player, for example:
http://www.npr.org/player/v2/mediaPlayer.html?action=1&t=1&islist=false&id=368714299&m=368931763
