### ISSUE TITLE
Amazon.com

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#64]
Hi,
The Iframely is not working for Amazon.com. Is there anyway to get it?

Regards,
Manik Mittal

**Comment by j0k3r** [comment]
I don't think Amazon provide an embed of their products.
If they do, please add this informaton in your issue.

**Comment by iparamonau** [comment]
Trust the question is why we don't provide a thumbnail for Amazon. Well, Amazon opted not to list thumbnails as Twitter Cards and/or OG image for their products. We respect their business strategy and do not parse pages to extract images. I trust it was a conscious choice by Amazon, not the lack of technical expertise :)

**Comment by manikmi** [comment]
Sorry guys for the late response. Yes, I agree with Ivan, we should respect their business strategy.
But, I saw something like this on embed.ly for amazon:

http://embed.ly/code?url=http%3A%2F%2Fwww.amazon.com%2FSteve-Jobs-Walter-Isaacson%2Fdp%2F1451648537

Can we have something like that card html generated on iframely as well?
Regards,
Manik Mittal
