### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#65]
Hi Ivan / Nazar,

Iframely open source code is not returning html for google maps even though I have entered the google maps key as mentioned on https://developers.google.com/maps/documentation/embed/guide#api_key
I have entered the api key in the google: maps_key and "google.maps" fields.

Is there anything I am doing wrong?

Truly appreciate your help.

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
New Google Maps plugin requires `google.maps_key` config. See [sample](https://github.com/itteco/iframely/blob/master/config.local.js.SAMPLE#L105). It might be the same as old `google.maps.apiKey` property I guess, but for legacy reasons, it is two separate fields.
