### ISSUE TITLE
CNN.com Videos

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#67]
Is there a way to get the html embed for CNN.Com videos? Like for example, the url
http://www.cnn.com/video/data/2.0/video/tech/2014/11/13/lklv-pleitgen-rosetta-spacecraft-latest.cnn.html
works fine and returns html code with embed.ly, but is failing with iframely.

**Comment by iparamonau** [comment]
We used to support CNN until their latest update. Now they don't publish embeds in open graph or even have the manual copy-paste embed codes on the page. 

We won't hack our way through and give you what the publisher doesn't commit to support. Especially if it's the old Flash code which is very likely to be deprecated soon.

But [CNN Money](http://money.cnn.com/video/technology/2015/01/13/3doodler-3d-pen.cnnmoney/index.html) and [CNN Mexico](http://mexico.cnn.com/videos/2013/12/09/bandas-organizadas-provocan-saqueos-en-argentina) are still supported

**Comment by manikmi** [comment]
Thanks,

Appreciate your support.

Regards,
Manik Mittal

On Wed, May 13, 2015 at 6:52 PM, Ivan Paramonau <notifications@github.com>
wrote:

> We used to support CNN until their latest update. Now they don't publish
> embeds in open graph or even have the manual copy-paste embed codes on the
> page.
>
> We won't hack our way through and give you what the publisher doesn't
> commit to support. Especially if it's the old Flash code which is very
> likely to be deprecated soon.
>
> But CNN Money
> <http://money.cnn.com/video/technology/2015/01/13/3doodler-3d-pen.cnnmoney/index.html>
> and CNN Mexico
> <http://mexico.cnn.com/videos/2013/12/09/bandas-organizadas-provocan-saqueos-en-argentina>
> are still supported
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itteco/iframely/issues/67#issuecomment-101661510>.
>



-- 
Regards,
Manik Mittal
