### ISSUE TITLE
Supporting Different Countries

### ISSUE THREAD

**Issue by frumania** [itteco/iframely#69]
Hi,

while most domains like facebook, youtube etc. automatically redirect to the ".com" domain, other web pages e.g. amazon have their "regional" domains e.g. ".co.uk" / ".es" etc.

Having just started to play around with custom plugins...
any way of allowing country specific matching (single file) opposed to writing multiple files per domain / region each ?!

Thanks for your help.
Some coding input would also be fine.

Thx.

**Comment by iparamonau** [comment]
The domain name in the plugin name is only used when you don't provide an array of regular expressions in `re` attribute of the plugin. 

So basically you can define anything. For example, take a look at [Getty Images plugin](https://github.com/itteco/iframely/blob/master/plugins/domains/gettyimages.com.js#L6)

**Comment by frumania** [comment]
Thanks :). Works!
