### ISSUE TITLE
Manually build an embed from datawrapper.de

### ISSUE THREAD

**Issue by j0k3r** [itteco/iframely#76]
I added datawrapper.de to our internal fork of Iframely few days ago but I don't think I did it in the best way...

For the background, [datawrapper](https://datawrapper.de/) is an open source tool to create chart from a source. Once you've finished polishing your chart, you can only grab the embed code where the embed url look like this: http://cf.datawrapper.de/zjCKi/2/

When I wanted to integrate it into Iframely, I noticed this line in the HTML source:

```html
<link rel="alternate" type="application/json+oembed" href="https://datawrapper.de/api/plugin/oembed?url=http%3A%2F%2Fcf.datawrapper.de%2FzjCKi%2F2%2F&amp;format=json" title="Montant total des amendes infligées par les régulateurs américains" />
```

Which was perfect for Iframely! Sadly, it leads to a 404 ...
I reached datawrapper support and they replyied:

> There is a module allowing for oEmbed, but it is like half-baked right now. If possible we would like to postpone work on this, there are more urgent tasks

:cry: 

So I started digging in the plugin creation to handle it on my own.
I created a file `plugins/domains/datawrapper.de.js` :

```js
module.exports = {
    re: [
        /^http[s]?:\/\/cf.datawrapper.de\/(.+?)(?:[\/](?:index\.html)?)?$/
    ],

    mixins: [
        "html-title"
    ],

    getLink: function(urlMatch, meta) {
        return {
            title: meta['html-title'],
            type: CONFIG.T.text_html,
            rel: CONFIG.R.inline,
            // href: "http://cf.datawrapper.de/" + urlMatch[1] + "/",
            html: '<iframe width="566" height="400" scrolling="no" frameborder="0" src="http://cf.datawrapper.de/' + urlMatch[1] + '/"></iframe>'
        }
    },

    getMeta: function(meta) {
        return {
            site: 'datawrapper',
        };
    },

    tests: [
        "http://cf.datawrapper.de/zjCKi/2/",
        "http://cf.datawrapper.de/Gx44C/21/",
        "http://cf.datawrapper.de/RrO5t/2/"
    ]
};
```

What I don't like in this snippet, is the way I manually built the iframe instead of letting Iframely to its job and wrapping it in a div, etc ..

How can I do that?

**Comment by iparamonau** [comment]
* You have `href` commented in your code. That was the right way to pass it as embed URL. Paired with `text/html` type, Iframely would no to convert it into iFrame. What you were missing is the sizing information. You could either give `"aspect-ratio"` in the object, or, say, just `height` to make the embed stretch 100% of the width. To make a fixed iFrame, you can just pass width & height. 

* `rel` inline is the secondary rel, which is meant to indicate whether embed can be rendered via JavaScript or not. You need a main one too. I suggest `[CONFIG.R.app, CONFIG.R.ssl, CONFIG.R.html5] `. The flag for inline/js status isn't necessary if you return data as href rather than html. Iframely knows that iFrames are JS-friendly.

* Last but not least, in v0.8.6 we added an option to use `"*"` as a mixin. It adds all generic mixins, and basically means that plugin will add an embed rather than take complete control: `mixins: ["*"]`

**Comment by j0k3r** [comment]
I've updated the domain file with your recommandations:

```js
module.exports = {
    re: [
        /^http[s]?:\/\/cf.datawrapper.de\/(.+?)(?:[\/](?:index\.html)?)?$/
    ],

    mixins: [
        "*"
    ],

    getLink: function(urlMatch) {
        return {
            type: CONFIG.T.text_html,
            rel: [CONFIG.R.app, CONFIG.R.ssl, CONFIG.R.html5],
            href: "http://cf.datawrapper.de/" + urlMatch[1] + "/",
            height: 350
        }
    },

    getMeta: function() {
        return {
            site: 'datawrapper',
        };
    },

    tests: [
        "http://cf.datawrapper.de/zjCKi/2/",
        "http://cf.datawrapper.de/Gx44C/21/",
        "http://cf.datawrapper.de/RrO5t/2/"
    ]
};
```

But it doesn't generate the iframe:

```json
{
    "meta": {
        "title": "Montant total des amendes infligées par les régulateurs américains",
        "canonical": "http://cf.datawrapper.de/zjCKi/2/"
    },
    "links": [
        {
            "href": "http://cf.datawrapper.de/favicon.ico",
            "type": "image",
            "rel": [
                "icon"
            ]
        }
    ]
}
```

**Comment by iparamonau** [comment]
That would mean that domain plugin isn't called. I suggest to verify the regex, perhaps escape dots `\.`? 
I just ran your code locally with `/^https?:\/\/cf\.datawrapper\.de\/([a-zA-Z0-9]+)\//i` and it works fine. Not sure if it's the correct one though.

Also, did you know there's a local debug tool at http://localhost:8061/debug ?

**Comment by iparamonau** [comment]
.@nleush mentions that your regex matches, but there might be another issue at Iframely core here.

There is a validator at Iframely core that removes embeds with iframe src = canonical address (or original URL). In your case, the `urlMatch[1]` would be like `zjCKi/2` and you'll end up having iFrame exactly the same as URL (from your tests). 

That validator is for generic parsers, especially for Open Graph. A lot of people just put og:video=canonical. Unfortunately, we can not remove this check. To work it around, you could add some query string to iFrame src, like `?for=iframely` or something.

**Comment by j0k3r** [comment]
Of course I know the debug tool, I mostly used to test the domain :wink: 

And THANKS for that point @nleush I started to dig into the core.js to find why my regex is valid outside IFramely but not inside.

It works great now.
Thanks guys :+1:

**Comment by j0k3r** [comment]
@iparamonau Should I submit a PR to add this domain in plugins?

**Comment by iparamonau** [comment]
@j0k3r Sure, would be great. Thanks!
