### ISSUE TITLE
Youtube Error 429

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#81]
Hi,
I started getting Error code 429 while getting data for any Youtube video. Can somebody please help urgently?

**Comment by iparamonau** [comment]
Remove/delete youtube plugin and it should start falling back to oEmbed rather then youtube API. 

Apparently you are over YouTube rate limit, as 429 is returned by them. See https://developers.google.com/youtube/v3/docs/core_errors

**Comment by manikmi** [comment]
Thanks the issue is resolved.
