### ISSUE TITLE
Some of the youtube videos are not working

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#84]
Hi,

Is there some reason, some of the youtube video embeds (~5%) are not working. Like for this url:
https://www.youtube.com/watch?v=TjUX3CeRUZI and
https://www.youtube.com/watch?v=nevGBkrQnCA
if I see the open source code version on my server, it shows up result for iframely as:

{
  "type": "video",
  "version": "1.0",
  "title": "Sleepsong by Secret Garden (with lyrics)",
  "author": "myraadrian",
  "provider_name": "YouTube",
  "description": "My gratefulness and respect to all the artists on the Internet. In Irish the word for a lullaby is SUANTRAI  sleepsong  a beautiful and simple way of describing what the song is meant to do  sing someone to sleep. The words are written by Brendan Graham. The Irish singer is Saoirse.",
  "url": "https://www.youtube.com/watch?v=TjUX3CeRUZI",
  "provider_url": "https://www.youtube.com"
}

But, this is working on iframely api access (http://iframe.ly/71Flhb.oembed). Is there some difference in the code?

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
If you go to YouTube and try to copy embed code from there, you will see that "embedding disabled by request". 

Hosted version shows a summary card, not an actual player either.

**Comment by manikmi** [comment]
Thanks, Truly appreciate your help.

On Wed, Jul 8, 2015 at 6:25 PM, Ivan Paramonau <notifications@github.com>
wrote:

> If you go to YouTube and try to copy embed code from there, you will see
> that "embedding disabled by request".
>
> Hosted version shows a summary card, not an actual player either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itteco/iframely/issues/84#issuecomment-119569416>.
>



-- 
Regards,
Manik Mittal
