### ISSUE TITLE
Flickr content is being returned as of type rich only

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#86]
Hi,

Sorry, If I am too repetitive.
I want to extract data for flickr as type photo or video. Is there some way?
I have tried removing the apiKey and it started showing the way I want.
Do you see any issues in using filckr embeds without key? Also, is there some way the flickr embeds could be done with key and get the types as photo and video?

Regards,
Manik Mittal

**Comment by iparamonau** [comment]
This issue is dragged for a bit. The start is in #57 and #59. 

Let's start with a few examples of the URLs so that we can be sure we discuss the same thing.

**Comment by iparamonau** [comment]
Again, don't get the picture of what the expectation is. 
Anyway, going to close this issue for now as since v.0.8.7 there's `&media=1` querystring param that should make API return direct simplest media possible, and that includes Flickr.
