### ISSUE TITLE
Youtube embeds are failing

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#89]
Hi, 

The youtube embeds are failing in the open source code if the pm2 service is ran on clustered mode for our aws server with 4 cores. It returns back the youtube error 429. The command used for pm2 is:
sudo pm2 start server.js --name "iframely" -i 0
If i run without -i 0, it works fine.

P.S. The service does not fail in the clustered and other embeds also don't fail.

Regards,
Manik Mittal

**Comment by nleush** [comment]
Hi.

Did you configured youtube api_key? See: https://github.com/itteco/iframely/blob/master/config.local.js.SAMPLE#L137

How many requests do you send? Can you show server console log from start to request end ('pm2 logs').

BTW: 429 Means "Too Many Requests"

**Comment by nleush** [comment]
Alternatively you can test iframely cluster.js app. It works same as pm2 -i 0

`pm2 start cluster.js`

**Comment by iparamonau** [comment]
With 4 threads and about 150 ms per YouTube video you can easily create 25 reqs/second for YouTube APIs. Not sure what their limit is, but guess that would be close. So you need to revise how you use the API, for example make sure the caching engine is configured properly. 

From our side (see commit):
 * Just removed dependency on oEmbed, which should eliminate 2nd API call per URL
 * Implemented a fallback to generic parsers on 429 error, perhaps you'll get any luck with plain HTML/Twitter cards/OG parser if the error occurs
