### ISSUE TITLE
Coub player doe not autostart with autoplay=1 (iframely API)

### ISSUE THREAD

**Issue by NikolayS** [itteco/iframely#90]
Per https://iframely.com/docs/parameters, one can use `autoplay=1` to make player start. 
But for Coub this doesn't work
Example: 
http://open.iframe.ly/api/iframely?url=https://coub.com/view/59wl5&api_key=XXXXXX&autoplay=1
– this call returns:
```
...
    "html": "<div style=\"left: 0px; width: 100%; height: 0px; position: relative; padding-bottom: 56.2493%;\"><iframe src=\"//cdn.iframe.ly/api/iframe?url=https%3A%2F%2Fcoub.com%2Fview%2F59wl5&amp;key=e73a91afeaa8747c3d0b69f4ec3baff6&amp;autoplay=true\" frameborder=\"0\" allowfullscreen=\"true\" webkitallowfullscreen=\"true\" mozallowfullscreen=\"true\" style=\"top: 0px; left: 0px; width: 100%; height: 100%; position: absolute;\"></iframe></div>"
}
```
And this HTML shows non-autostarted player. 

BTW, Coub.com itself provides option `autostart=1` (not `autoplay`).

**Comment by iparamonau** [comment]
Fixed through central whitelist settings for Coub. You should get something like: iframe.ly/q9hi8S?autoplay=true&iframe=1 after CDN clears itself. 

BTW, if you use it with api_key your endpoint should be http://iframe.ly/api/iframely, not the open.* one.

**Comment by NikolayS** [comment]
Thanks
