### ISSUE TITLE
Timeout / redirect loop for a vk.com page

### ISSUE THREAD

**Issue by NikolayS** [itteco/iframely#91]
For request http://iframe.ly/api/iframely?url=http://vk.com/photo-27744747_376634226&api_key=XXX the following is returned:
```
{
    "status": 408,
    "error": "Requested page error: timeout"
}
```

I also tried it on my own installation of iframely and see (for http://HOSTNAME/iframely?url=http://vk.com/photo-27744747_376634226):
```
Requested page error: timeout
```

More interesting, if we add `autoplay=` GET param (http://HOSTNAME/iframely?url=http://vk.com/photo-27744747_376634226&autoplay=1) we got this error after some time of waiting:
```
Requested page error: redirect loop
```

**Comment by NikolayS** [comment]
The response is unpredictable, it mentions either redirect loop or timeout and I haven't yet found the exact circumstances.

it can be like this:
![screenshot 2015-08-21 13 00 11](https://cloud.githubusercontent.com/assets/1345402/9405934/bf2e320c-4804-11e5-8f2c-d1ee36b8fc18.png)

... or this:
![screenshot 2015-08-21 13 00 16](https://cloud.githubusercontent.com/assets/1345402/9405940/c8b419cc-4804-11e5-923c-042cd02cefc4.png)

**Comment by iparamonau** [comment]
Argh. VK started to re-direct Iframely's user-agent to their mobile version. Here's what happens afterwards:

```
--  Loading /iframely for http://vk.com/photo-27744747_376634226
   -- plugin redirect (by "htmlparser") http://m.vk.com/photo-27744747_376634226
   -- plugin redirect (by "mobile-canonical") http://vk.com/photo-27744747_376634226?=
   -- plugin redirect (by "htmlparser") http://m.vk.com/photo-27744747_376634226
   -- plugin redirect (by "mobile-canonical") http://vk.com/photo-27744747_376634226?=
   -- plugin redirect (by "htmlparser") http://m.vk.com/photo-27744747_376634226
Requested page error: redirect loop
```

We'll do a fix. Thanks for heads up.

**Comment by iparamonau** [comment]
Pushed to `dev` and to the cloud copy. 

As a bonus, you should now be getting proper images for vk photos. 

BTW, wall post embeds for VK do work if you add ?hash=... to URL, where hash needs to grabbed from vk manually.

**Comment by NikolayS** [comment]
Thank you
